import type { Course } from "../../../domain/curriculum";
import { javaLesson } from "../shared";

const courseId = "course_java_grade_2";
const chapterId = "chapter_java2_practical";

const discountStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static int discountedPrice(int price, int rate) {\n    return price;\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int price = scanner.nextInt();\n    int rate = scanner.nextInt();\n    System.out.println(discountedPrice(price, rate));\n  }\n}\n";
const labelStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static String scoreLabel(String name, int score) {\n    return name + \":\" + score;\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    String name = scanner.nextLine();\n    int score = scanner.nextInt();\n    System.out.println(scoreLabel(name, score));\n  }\n}\n";
const validationStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static String grade(int score) {\n    if (score >= 80) {\n      return \"A\";\n    }\n    return \"C\";\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int score = scanner.nextInt();\n    System.out.println(grade(score));\n  }\n}\n";
const sumStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static int sumCsv(String line) {\n    String[] parts = line.split(\",\");\n    int total = 0;\n    for (int i = 0; i < parts.length; i++) {\n      total = total + Integer.parseInt(parts[i]);\n    }\n    return total;\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    System.out.println(sumCsv(scanner.nextLine()));\n  }\n}\n";
const maxStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int[] scores = {scanner.nextInt(), scanner.nextInt(), scanner.nextInt()};\n    int best = 0;\n    for (int i = 0; i < scores.length; i++) {\n      if (scores[i] < best) {\n        best = scores[i];\n      }\n    }\n    System.out.println(best);\n  }\n}\n";
const projectStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static int sumCsv(String line) {\n    String[] parts = line.split(\",\");\n    int total = 0;\n    for (int i = 0; i < parts.length; i++) {\n      total = total + Integer.parseInt(parts[i]);\n    }\n    return total;\n  }\n\n  public static int countCsv(String line) {\n    return line.split(\",\").length;\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    String line = scanner.nextLine();\n    int count = countCsv(line);\n    int total = sumCsv(line);\n    System.out.println(\"count:\" + count + \",avg:\" + Math.floor(total / count));\n  }\n}\n";

export const javaGrade2Course: Course = {
  id: courseId,
  languageId: "lang_java",
  levelId: "level_java_2",
  title: "Java 2級",
  description: "Javaのメソッド分割、配列処理、デバッグ、小さな集計課題を練習します。",
  curriculumVersion: "java-grade-2-v0.1.0",
  validFrom: "2026-09-05",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "Java 2級 実践基礎",
      description: "処理をメソッドへ分け、入力値を検証し、配列やCSV文字列を使う実践課題です。",
      order: 1,
      lessons: [
        javaLesson(chapterId, {
          id: "lesson_java2_01_method_return",
          slug: "method-return",
          title: "Lesson 01: メソッドの戻り値",
          objective: "引数を受け取るstaticメソッドで計算結果を返せる。",
          explanationMd: "戻り値のあるメソッドではreturnで値を呼び出し元へ返します。",
          taskMd: "priceとrateを受け取り、割引後価格を整数で出力してください。",
          starterCode: discountStarter,
          sampleInput: "2000\n10\n",
          sampleOutput: "1800\n",
          constraints: ["discountedPrice(price, rate)を使ってください。", "Math.floor()で整数にしてください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 1,
          hints: ["割引後は price * (100 - rate) / 100 です。", "return Math.floor(...); の形にします。"],
          exercises: [{ id: "ex_java2_01_01", promptMd: "割引後価格を計算して返します。", starterCode: discountStarter, completionCriteria: "公開/hidden入力で割引後価格が一致する。", testCases: [{ id: "tc_java2_01_public", order: 1, visibility: "public", stdin: "2000\n10\n", expectedStdout: "1800\n" }, { id: "tc_java2_01_hidden", order: 2, visibility: "hidden", stdin: "2500\n20\n", expectedStdout: "2000\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java2_02_method_composition",
          slug: "method-composition",
          title: "Lesson 02: method composition",
          objective: "条件分岐をメソッド内へまとめ、呼び出し元を読みやすくできる。",
          explanationMd: "メソッドに判定を閉じ込めると、mainメソッドは入力と出力に集中できます。",
          taskMd: "scoreLabel(name, score)が80以上なら name + \":A\"、それ以外なら name + \":B\" を返すようにしてください。",
          starterCode: labelStarter,
          sampleInput: "Aki\n82\n",
          sampleOutput: "Aki:A\n",
          constraints: ["scoreLabel()の戻り値を直してください。", "mainからscoreLabel()を呼び出してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 2,
          hints: ["if (score >= 80) を使います。", "Aのときは return name + \":A\"; です。"],
          exercises: [{ id: "ex_java2_02_01", promptMd: "名前と点数から評価ラベルを返します。", starterCode: labelStarter, completionCriteria: "A/B両方のケースに合格する。", testCases: [{ id: "tc_java2_02_public", order: 1, visibility: "public", stdin: "Aki\n82\n", expectedStdout: "Aki:A\n" }, { id: "tc_java2_02_hidden", order: 2, visibility: "hidden", stdin: "Sora\n70\n", expectedStdout: "Sora:B\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java2_03_input_validation",
          slug: "input-validation",
          title: "Lesson 03: input validation",
          objective: "境界値を意識して条件分岐を直せる。",
          explanationMd: "条件の境界値をテストすると、分類の抜けに気づきやすくなります。",
          taskMd: "grade(score)が80以上でA、60以上でB、それ未満でCを返すようにしてください。",
          starterCode: validationStarter,
          sampleInput: "72\n",
          sampleOutput: "B\n",
          constraints: ["80以上、60以上、それ未満の順に判定してください。", "出力はA/B/Cのどれか1行です。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 3,
          hints: ["score >= 60 の条件を追加します。", "80以上の判定を先に書きます。"],
          exercises: [{ id: "ex_java2_03_01", promptMd: "点数からA/B/Cを返します。", starterCode: validationStarter, completionCriteria: "境界を含む公開/hiddenケースに合格する。", testCases: [{ id: "tc_java2_03_public", order: 1, visibility: "public", stdin: "72\n", expectedStdout: "B\n" }, { id: "tc_java2_03_hidden", order: 2, visibility: "hidden", stdin: "59\n", expectedStdout: "C\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java2_04_array_sum",
          slug: "array-sum",
          title: "Lesson 04: array sum",
          objective: "CSV文字列を配列に分け、forで合計できる。",
          explanationMd: "split(\",\")で文字列を配列に分け、Integer.parseInt()で整数へ変換できます。",
          taskMd: "カンマ区切りの整数を受け取り、合計を出力してください。",
          starterCode: sumStarter,
          sampleInput: "10,20,30\n",
          sampleOutput: "60\n",
          constraints: ["split(\",\")を使ってください。", "forでpartsを順番に処理してください。"],
          difficulty: 3,
          estimatedMinutes: 20,
          order: 4,
          hints: ["parts[i]をInteger.parseInt()へ渡します。", "total = total + ... で足し込みます。"],
          exercises: [{ id: "ex_java2_04_01", promptMd: "CSVの数値を合計します。", starterCode: sumStarter, completionCriteria: "複数のCSV入力で合計が一致する。", testCases: [{ id: "tc_java2_04_public", order: 1, visibility: "public", stdin: "10,20,30\n", expectedStdout: "60\n" }, { id: "tc_java2_04_hidden", order: 2, visibility: "hidden", stdin: "4,5,6\n", expectedStdout: "15\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java2_05_algorithm_debug",
          slug: "algorithm-debug",
          title: "Lesson 05: algorithm debug",
          objective: "最大値探索のバグをテストから見つけて修正できる。",
          explanationMd: "最大値を探すときは初期値と比較演算子の向きが大切です。",
          taskMd: "3つの整数を受け取り、最大値を出力するようにバグを直してください。",
          starterCode: maxStarter,
          sampleInput: "4\n9\n2\n",
          sampleOutput: "9\n",
          constraints: ["scores配列を使ってください。", "bestは配列の値から始めてください。", "大きい値を見つけたときだけbestを更新してください。"],
          difficulty: 3,
          estimatedMinutes: 20,
          order: 5,
          hints: ["best = scores[0] から始めると負数にも対応できます。", "比較は scores[i] > best です。"],
          exercises: [{ id: "ex_java2_05_01", promptMd: "最大値探索のバグを修正します。", starterCode: maxStarter, completionCriteria: "正数とhiddenの負数ケースに合格する。", testCases: [{ id: "tc_java2_05_public", order: 1, visibility: "public", stdin: "4\n9\n2\n", expectedStdout: "9\n" }, { id: "tc_java2_05_hidden", order: 2, visibility: "hidden", stdin: "-4\n-2\n-9\n", expectedStdout: "-2\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java2_06_small_project",
          slug: "small-project",
          title: "Lesson 06: small project",
          objective: "複数メソッドを組み合わせて小さな集計プログラムを完成できる。",
          explanationMd: "入力、分割、合計、件数、平均を小さなメソッドに分けると、処理を確認しやすくなります。",
          taskMd: "カンマ区切りの点数を受け取り、countと平均を count:3,avg:80 の形式で出力してください。",
          starterCode: projectStarter,
          sampleInput: "70,80,90\n",
          sampleOutput: "count:3,avg:80\n",
          constraints: ["countCsv()とsumCsv()を使ってください。", "平均はMath.floor(total / count)で整数にしてください。"],
          difficulty: 3,
          estimatedMinutes: 25,
          order: 6,
          hints: ["countはsplitした配列のlengthです。", "平均は合計を件数で割ります。"],
          exercises: [{ id: "ex_java2_06_01", promptMd: "CSVの点数から件数と平均を出力します。", starterCode: projectStarter, completionCriteria: "公開/hiddenのCSV入力で件数と平均が一致する。", testCases: [{ id: "tc_java2_06_public", order: 1, visibility: "public", stdin: "70,80,90\n", expectedStdout: "count:3,avg:80\n" }, { id: "tc_java2_06_hidden", order: 2, visibility: "hidden", stdin: "60,90,100,70\n", expectedStdout: "count:4,avg:80\n" }] }],
        }),
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
