import type { Course } from "../../../domain/curriculum";

const courseId = "course_python_grade_2";

export const pythonGrade2Course: Course = {
  id: courseId,
  languageId: "lang_python",
  levelId: "level_python_2",
  title: "Python 2級",
  description: "関数の深掘り、class、例外、仮想ファイルI/O、アルゴリズムへ進むためのPython 2級コースです。",
  curriculumVersion: "0.1.0",
  validFrom: "2026-09-04",
  chapters: [
    {
      id: "chapter_python_grade_2_foundation",
      courseId,
      title: "Python 2級 Foundation",
      description: "関数の戻り値、引数、責務分割を深掘りするChapterです。",
      order: 1,
      lessons: [
        {
          id: "lesson_py2_01_function_return",
          chapterId: "chapter_python_grade_2_foundation",
          slug: "function-return",
          title: "Lesson 01: 関数の戻り値",
          objective: "計算を関数へ切り出し、戻り値を使って結果を出力する。",
          explanationMd: "2級では、処理をただ順番に書くのではなく、名前を付けた関数へ分けて再利用できる形にします。return は関数の計算結果を呼び出し元へ返すために使います。",
          taskMd: "価格 price と割引率 rate を整数で受け取り、discounted_price(price, rate) 関数で割引後の価格を計算して出力してください。",
          starterCode: "def discounted_price(price, rate):\n    return price\n\nprice = int(input())\nrate = int(input())\nprint(discounted_price(price, rate))\n",
          sampleInput: "1000\n10\n",
          sampleOutput: "900\n",
          constraints: [
            "discounted_price(price, rate) 関数を定義してください。",
            "関数の中で return を使って計算結果を返してください。",
            "割引後の価格は price * (100 - rate) // 100 で整数として計算してください。",
            "出力は割引後の価格を1行にしてください。",
          ],
          difficulty: 2,
          estimatedMinutes: 12,
          order: 1,
          status: "published",
          hints: [
            "rate は割引率なので、支払う割合は 100 - rate です。",
            "関数の return に price * (100 - rate) // 100 を書くと整数の価格を返せます。",
            "入力を受け取る部分と、計算する関数を分けて考えましょう。",
          ],
          exercises: [
            {
              id: "ex_py2_01_01",
              lessonId: "lesson_py2_01_function_return",
              type: "code",
              promptMd: "discounted_price 関数の戻り値で割引後の価格を出力します。",
              starterCode: "def discounted_price(price, rate):\n    return price\n\nprice = int(input())\nrate = int(input())\nprint(discounted_price(price, rate))\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の価格と割引率で、整数の割引後価格を正しく出力する。",
              testCases: [
                {
                  id: "tc_py2_01_public",
                  order: 1,
                  visibility: "public",
                  stdin: "1000\n10\n",
                  expectedStdout: "900\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py2_01_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "2500\n20\n",
                  expectedStdout: "2000\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py2_02_classes",
          chapterId: "chapter_python_grade_2_foundation",
          slug: "classes",
          title: "Lesson 02: class",
          objective: "classでデータと処理をまとめ、objectのメソッドを呼び出す。",
          explanationMd: "class は、関連するデータと処理を1つの型としてまとめるために使います。__init__ でobjectの初期値を受け取り、self を通して属性やメソッドを扱います。",
          taskMd: "Student class を作り、name と score を受け取って保存してください。label() メソッドで `name:score` の形の文字列を返し、その結果を出力してください。",
          starterCode: "class Student:\n    def __init__(self, name, score):\n        self.name = name\n        self.score = score\n\n    def label(self):\n        return self.name\n\nname = input()\nscore = int(input())\nstudent = Student(name, score)\nprint(student.label())\n",
          sampleInput: "Aki\n82\n",
          sampleOutput: "Aki:82\n",
          constraints: [
            "Student class を定義してください。",
            "__init__(self, name, score) で name と score を属性に保存してください。",
            "label(self) メソッドで `name:score` の文字列を return してください。",
            "作成した student object の label() を呼び出して出力してください。",
          ],
          difficulty: 3,
          estimatedMinutes: 15,
          order: 2,
          status: "published",
          hints: [
            "score は数値ですが、文字列へつなげるときは str(self.score) が必要です。",
            "label の return は self.name + \":\" + str(self.score) の形にできます。",
            "self.name と self.score は __init__ で代入したobjectごとの値です。",
          ],
          exercises: [
            {
              id: "ex_py2_02_01",
              lessonId: "lesson_py2_02_classes",
              type: "code",
              promptMd: "Student objectのメソッドで、名前と点数をまとめた表示ラベルを返します。",
              starterCode: "class Student:\n    def __init__(self, name, score):\n        self.name = name\n        self.score = score\n\n    def label(self):\n        return self.name\n\nname = input()\nscore = int(input())\nstudent = Student(name, score)\nprint(student.label())\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の名前と点数で `name:score` の形式を正しく出力する。",
              testCases: [
                {
                  id: "tc_py2_02_public",
                  order: 1,
                  visibility: "public",
                  stdin: "Aki\n82\n",
                  expectedStdout: "Aki:82\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py2_02_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "Ren\n95\n",
                  expectedStdout: "Ren:95\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py2_03_exceptions",
          chapterId: "chapter_python_grade_2_foundation",
          slug: "exceptions",
          title: "Lesson 03: exception",
          objective: "try/exceptで変換エラーを受け止め、処理を安全に続ける。",
          explanationMd: "例外は、プログラムの途中で起きた特別なエラー状態です。try に失敗する可能性がある処理を書き、except ValueError で整数へ変換できない入力を受け止めると、プログラムを止めずに別の結果を返せます。",
          taskMd: "1行の入力 value を受け取り、整数へ変換できる場合は `number:<整数>`、変換できない場合は `invalid` と出力してください。変換処理は try/except ValueError で扱ってください。",
          starterCode: "value = input()\n\ntry:\n    number = int(value)\n    print(number)\nexcept ValueError:\n    print(\"error\")\n",
          sampleInput: "42\n",
          sampleOutput: "number:42\n",
          constraints: [
            "int(value) は try の中で実行してください。",
            "except ValueError で変換できない入力を受け止めてください。",
            "整数へ変換できる場合は `number:<整数>` を出力してください。",
            "整数へ変換できない場合は `invalid` を出力してください。",
          ],
          difficulty: 3,
          estimatedMinutes: 14,
          order: 3,
          status: "published",
          hints: [
            "変換できる場合は number = int(value) のあとに print(\"number:\" + str(number)) を実行できます。",
            "ValueError は int(\"abc\") のように整数へ変換できない文字列で起きます。",
            "except ValueError: の中では print(\"invalid\") と書くと、エラーの代わりに案内を出せます。",
          ],
          exercises: [
            {
              id: "ex_py2_03_01",
              lessonId: "lesson_py2_03_exceptions",
              type: "code",
              promptMd: "try/exceptで入力変換を守り、数値と不正入力を別々に出力します。",
              starterCode: "value = input()\n\ntry:\n    number = int(value)\n    print(number)\nexcept ValueError:\n    print(\"error\")\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "整数入力と整数ではない入力の両方で、指定されたメッセージを正しく出力する。",
              testCases: [
                {
                  id: "tc_py2_03_public",
                  order: 1,
                  visibility: "public",
                  stdin: "42\n",
                  expectedStdout: "number:42\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py2_03_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "oops\n",
                  expectedStdout: "invalid\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py2_04_virtual_file_io",
          chapterId: "chapter_python_grade_2_foundation",
          slug: "virtual-file-io",
          title: "Lesson 04: virtual file I/O",
          objective: "ブラウザ内の仮想ファイルへ書き込み、同じ実行内で読み戻す。",
          explanationMd: "Python では open() を使ってファイルを読み書きできます。このTrainerでは、学習用コードはブラウザ内のPython workerで動きます。ここで扱うファイルは `report.txt` のような相対名の仮想ファイルで、PC上の実ファイルを直接読み書きしません。",
          taskMd: "name と score を入力で受け取り、`report.txt` に `name,score` の形式で書き込んでください。その後、同じファイルを読み戻し、`saved:<内容>` の形式で出力してください。",
          starterCode: "name = input()\nscore = input()\n\nwith open(\"report.txt\", \"w\", encoding=\"utf-8\") as file:\n    file.write(name)\n\nwith open(\"report.txt\", \"r\", encoding=\"utf-8\") as file:\n    line = file.read()\n\nprint(\"saved:\" + line)\n",
          sampleInput: "Aki\n82\n",
          sampleOutput: "saved:Aki,82\n",
          constraints: [
            "`report.txt` のような相対ファイル名を使ってください。",
            "書き込みは with open(\"report.txt\", \"w\", encoding=\"utf-8\") の形で行ってください。",
            "読み込みは with open(\"report.txt\", \"r\", encoding=\"utf-8\") の形で行ってください。",
            "出力は読み戻した内容に `saved:` を付けた1行にしてください。",
          ],
          difficulty: 3,
          estimatedMinutes: 16,
          order: 4,
          status: "published",
          hints: [
            "file.write(name + \",\" + score) とすると、2つの値をカンマ区切りで保存できます。",
            "read() はファイル全体を文字列として読み込みます。",
            "保存した文字列を line に入れたら、print(\"saved:\" + line) で結果を確認できます。",
          ],
          exercises: [
            {
              id: "ex_py2_04_01",
              lessonId: "lesson_py2_04_virtual_file_io",
              type: "code",
              promptMd: "ブラウザ内の仮想ファイルへ学習記録を書き込み、読み戻して出力します。",
              starterCode: "name = input()\nscore = input()\n\nwith open(\"report.txt\", \"w\", encoding=\"utf-8\") as file:\n    file.write(name)\n\nwith open(\"report.txt\", \"r\", encoding=\"utf-8\") as file:\n    line = file.read()\n\nprint(\"saved:\" + line)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の名前と点数で、仮想ファイルへ保存した内容を読み戻して正しく出力する。",
              testCases: [
                {
                  id: "tc_py2_04_public",
                  order: 1,
                  visibility: "public",
                  stdin: "Aki\n82\n",
                  expectedStdout: "saved:Aki,82\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py2_04_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "Mina\n91\n",
                  expectedStdout: "saved:Mina,91\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py2_05_algorithm_debug",
          chapterId: "chapter_python_grade_2_foundation",
          slug: "algorithm-debug",
          title: "Lesson 05: algorithm debug",
          objective: "リストを走査するアルゴリズムのバグを見つけ、正しい最大値を返す。",
          explanationMd: "アルゴリズムのdebugでは、コードがどの値を順番に見ているか、変数がいつ更新されるかを追います。最大値を探す処理では、最初の候補値と比較条件が特に重要です。",
          taskMd: "スペース区切りの整数を読み取り、highest_score(scores) 関数で最大値を返してください。starter codeにはバグがあります。負の数だけの入力でも正しい最大値を出力できるように直してください。",
          starterCode: "scores = [int(value) for value in input().split()]\n\ndef highest_score(scores):\n    best = 0\n    for score in scores:\n        if score < best:\n            best = score\n    return best\n\nprint(highest_score(scores))\n",
          sampleInput: "3 8 5\n",
          sampleOutput: "8\n",
          constraints: [
            "highest_score(scores) 関数を残してください。",
            "scores の全要素を確認して最大値を返してください。",
            "負の数だけの入力でも正しく動くようにしてください。",
            "出力は最大値だけを1行にしてください。",
          ],
          difficulty: 4,
          estimatedMinutes: 18,
          order: 5,
          status: "published",
          hints: [
            "best を 0 で始めると、すべて負の数のときに存在しない0を返してしまいます。",
            "最初の候補は scores[0] にすると、入力にある値から比較を始められます。",
            "最大値を探す比較条件は、score が best より大きいときに更新します。",
          ],
          exercises: [
            {
              id: "ex_py2_05_01",
              lessonId: "lesson_py2_05_algorithm_debug",
              type: "code",
              promptMd: "最大値探索のバグを直し、正の数でも負の数でも正しい結果を返します。",
              starterCode: "scores = [int(value) for value in input().split()]\n\ndef highest_score(scores):\n    best = 0\n    for score in scores:\n        if score < best:\n            best = score\n    return best\n\nprint(highest_score(scores))\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "通常の数列と負数だけの数列の両方で、最大値を正しく出力する。",
              testCases: [
                {
                  id: "tc_py2_05_public",
                  order: 1,
                  visibility: "public",
                  stdin: "3 8 5\n",
                  expectedStdout: "8\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py2_05_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "-4 -2 -9\n",
                  expectedStdout: "-2\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
