import { createHtmlCssCourse, type HtmlCssLessonSeed } from "../shared";

const chapterId = "chapter_html_css_grade_2_layout";

const lessons: HtmlCssLessonSeed[] = [
  {
    id: "lesson_htmlcss2_01_responsive_cards",
    slug: "responsive-cards",
    title: "Lesson 01: responsive cards",
    objective: "カード一覧をflexとmedia queryで読みやすく配置する。",
    task: "card-gridを通常は横並び、狭い画面では縦並びにしてください。",
    html: "<section class=\"card-grid\">\n  <article class=\"info-card\"><h2>HTML</h2><p>構造を作ります。</p></article>\n  <article class=\"info-card\"><h2>CSS</h2><p>見た目を整えます。</p></article>\n</section>\n",
    css: ".card-grid {\n  display: flex;\n  gap: 16px;\n}\n\n.info-card {\n  padding: 20px;\n  border: 1px solid #176b87;\n}\n\n@media (max-width: 700px) {\n  .card-grid {\n    display: block;\n  }\n}\n",
    domRequirements: [
      { id: "cards-grid", order: 1, visibility: "public", kind: "selector_exists", selector: "section.card-grid", description: "card-grid sectionがある。", required: true },
      { id: "cards-card", order: 2, visibility: "public", kind: "selector_exists", selector: ".card-grid .info-card", description: "info-cardがある。", required: true },
      { id: "cards-second", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".card-grid .info-card:nth-child(2)", description: "2枚目のカードがある。", required: true },
    ],
    styleRequirements: [
      { id: "cards-flex", order: 4, visibility: "public", kind: "declaration_equals", selector: ".card-grid", property: "display", expectedValue: "flex", description: "カードを横並びにする。", required: true },
      { id: "cards-responsive", order: 5, visibility: "hidden", kind: "media_declaration_equals", mediaQuery: "(max-width: 700px)", selector: ".card-grid", property: "display", expectedValue: "block", description: "狭い画面では縦並びにする。", required: true },
    ],
    order: 1,
    difficulty: 2,
    estimatedMinutes: 18,
    hints: ["カード一覧の親要素にdisplay:flexを指定します。", "gapでカード同士の間隔を作ります。", "media queryの中でdisplay:blockに戻します。"],
  },
  {
    id: "lesson_htmlcss2_02_accessible_form",
    slug: "accessible-form",
    title: "Lesson 02: accessible form",
    objective: "fieldset、legend、labelで入力フォームの意味を明確にする。",
    task: "問い合わせフォームにlegendとlabelを置き、入力欄の余白をCSSで整えてください。",
    html: "<form class=\"contact-form\">\n  <fieldset>\n    <legend>問い合わせ</legend>\n    <label for=\"message\">内容</label>\n    <textarea id=\"message\" name=\"message\"></textarea>\n  </fieldset>\n</form>\n",
    css: ".contact-form fieldset {\n  display: grid;\n  gap: 10px;\n  padding: 18px;\n}\n\n.contact-form textarea {\n  min-height: 120px;\n}\n",
    domRequirements: [
      { id: "form-fieldset", order: 1, visibility: "public", kind: "selector_exists", selector: ".contact-form fieldset", description: "fieldsetがある。", required: true },
      { id: "form-legend", order: 2, visibility: "public", kind: "text_includes", selector: ".contact-form legend", expectedText: "問い合わせ", description: "legendでフォームの目的が示されている。", required: true },
      { id: "form-textarea", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".contact-form textarea#message", description: "message用textareaがある。", required: true },
    ],
    styleRequirements: [
      { id: "form-grid", order: 4, visibility: "public", kind: "declaration_equals", selector: ".contact-form fieldset", property: "display", expectedValue: "grid", description: "fieldsetをgridにする。", required: true },
      { id: "form-textarea-height", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".contact-form textarea", property: "min-height", expectedValue: "120px", description: "textareaに十分な高さがある。", required: true },
    ],
    order: 2,
    difficulty: 2,
    estimatedMinutes: 18,
    hints: ["fieldsetは関連する入力欄をまとめます。", "legendはそのグループの見出しです。", "labelのforとtextareaのidを揃えます。"],
  },
  {
    id: "lesson_htmlcss2_03_navigation_layout",
    slug: "navigation-layout",
    title: "Lesson 03: navigation layout",
    objective: "header内のnavをflexで配置する。",
    task: "site-headerの中にロゴとnavを置き、nav-listを横並びにしてください。",
    html: "<header class=\"site-header\">\n  <strong class=\"logo\">PT</strong>\n  <nav aria-label=\"Main navigation\">\n    <ul class=\"nav-list\"><li><a href=\"#home\">Home</a></li><li><a href=\"#lessons\">Lessons</a></li></ul>\n  </nav>\n</header>\n",
    css: ".site-header {\n  display: flex;\n  justify-content: space-between;\n}\n\n.nav-list {\n  display: flex;\n  gap: 14px;\n}\n",
    domRequirements: [
      { id: "site-header", order: 1, visibility: "public", kind: "selector_exists", selector: "header.site-header", description: "site-headerがある。", required: true },
      { id: "site-nav", order: 2, visibility: "public", kind: "selector_exists", selector: ".site-header nav", description: "header内にnavがある。", required: true },
      { id: "site-nav-second", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".nav-list li:nth-child(2) a", description: "2つ目のnavリンクがある。", required: true },
    ],
    styleRequirements: [
      { id: "site-header-flex", order: 4, visibility: "public", kind: "declaration_equals", selector: ".site-header", property: "display", expectedValue: "flex", description: "headerをflexにする。", required: true },
      { id: "site-nav-gap", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".nav-list", property: "gap", expectedValue: "14px", description: "navリンク間のgapがある。", required: true },
    ],
    order: 3,
    difficulty: 2,
    estimatedMinutes: 18,
    hints: ["headerをflexにするとロゴとnavを横に並べられます。", "ulにもdisplay:flexを指定できます。", "justify-contentで左右配置を調整できます。"],
  },
  {
    id: "lesson_htmlcss2_04_table_state",
    slug: "table-state",
    title: "Lesson 04: table state",
    objective: "tableで進捗一覧を作り、状態表示をCSSで強調する。",
    task: "progress-tableにthead/tbodyを置き、done状態のセルを目立たせてください。",
    html: "<table class=\"progress-table\">\n  <thead><tr><th>Lesson</th><th>Status</th></tr></thead>\n  <tbody><tr><td>HTML</td><td class=\"state-done\">Done</td></tr></tbody>\n</table>\n",
    css: ".progress-table {\n  border-collapse: collapse;\n}\n\n.state-done {\n  font-weight: 700;\n  color: #176b87;\n}\n",
    domRequirements: [
      { id: "progress-table", order: 1, visibility: "public", kind: "selector_exists", selector: "table.progress-table", description: "progress-tableがある。", required: true },
      { id: "progress-head", order: 2, visibility: "public", kind: "selector_exists", selector: ".progress-table thead th", description: "table headerがある。", required: true },
      { id: "progress-state", order: 3, visibility: "hidden", kind: "text_includes", selector: ".state-done", expectedText: "Done", description: "Done状態がある。", required: true },
    ],
    styleRequirements: [
      { id: "progress-collapse", order: 4, visibility: "public", kind: "declaration_equals", selector: ".progress-table", property: "border-collapse", expectedValue: "collapse", description: "セル境界をまとめる。", required: true },
      { id: "progress-bold", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".state-done", property: "font-weight", expectedValue: "700", description: "完了状態が強調されている。", required: true },
    ],
    order: 4,
    difficulty: 2,
    estimatedMinutes: 18,
    hints: ["表の見出しはtheadに入れます。", "データ行はtbodyに入れます。", "状態セルにclassを付けるとCSSで強調できます。"],
  },
  {
    id: "lesson_htmlcss2_05_component_variants",
    slug: "component-variants",
    title: "Lesson 05: component variants",
    objective: "共通classとmodifier classで部品のバリエーションを作る。",
    task: "button-rowにprimary/secondaryの2種類のリンクボタンを配置してください。",
    html: "<div class=\"button-row\">\n  <a class=\"button button-primary\" href=\"#start\">Start</a>\n  <a class=\"button button-secondary\" href=\"#later\">Later</a>\n</div>\n",
    css: ".button {\n  display: inline-block;\n  padding: 10px 14px;\n}\n\n.button-primary {\n  background: #176b87;\n}\n\n.button-secondary {\n  background: #64748b;\n}\n",
    domRequirements: [
      { id: "button-primary", order: 1, visibility: "public", kind: "selector_exists", selector: ".button.button-primary", description: "primaryボタンがある。", required: true },
      { id: "button-secondary", order: 2, visibility: "public", kind: "selector_exists", selector: ".button.button-secondary", description: "secondaryボタンがある。", required: true },
      { id: "button-row", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".button-row a:nth-child(2)", description: "2つ目のボタンがある。", required: true },
    ],
    styleRequirements: [
      { id: "button-display", order: 4, visibility: "public", kind: "declaration_equals", selector: ".button", property: "display", expectedValue: "inline-block", description: "共通buttonはinline-block。", required: true },
      { id: "button-padding", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".button", property: "padding", expectedValue: "10px 14px", description: "共通buttonに余白がある。", required: true },
    ],
    order: 5,
    difficulty: 2,
    estimatedMinutes: 18,
    hints: ["共通の見た目は.buttonに書きます。", "違う見た目だけ.button-primaryへ書きます。", "1つの要素に複数classを付けられます。"],
  },
  {
    id: "lesson_htmlcss2_06_small_page",
    slug: "small-page",
    title: "Lesson 06: small page",
    objective: "複数sectionを組み合わせて小さな情報ページを作る。",
    task: "page-shell内にintroとlesson-cardsを配置し、section間の余白を整えてください。",
    html: "<main class=\"page-shell\">\n  <section class=\"intro\"><h1>HTML/CSS Practice</h1><p>小さなページを作ります。</p></section>\n  <section class=\"lesson-cards\"><article>Structure</article><article>Style</article></section>\n</main>\n",
    css: ".page-shell {\n  display: grid;\n  gap: 24px;\n}\n\n.lesson-cards {\n  display: flex;\n  gap: 16px;\n}\n\n@media (max-width: 700px) {\n  .lesson-cards {\n    display: block;\n  }\n}\n",
    domRequirements: [
      { id: "page-shell", order: 1, visibility: "public", kind: "selector_exists", selector: "main.page-shell", description: "page-shellのmainがある。", required: true },
      { id: "page-intro", order: 2, visibility: "public", kind: "selector_exists", selector: ".page-shell .intro h1", description: "intro見出しがある。", required: true },
      { id: "page-cards-second", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".lesson-cards article:nth-child(2)", description: "2つ目のカードがある。", required: true },
    ],
    styleRequirements: [
      { id: "page-shell-gap", order: 4, visibility: "public", kind: "declaration_equals", selector: ".page-shell", property: "gap", expectedValue: "24px", description: "section間のgapがある。", required: true },
      { id: "page-responsive", order: 5, visibility: "hidden", kind: "media_declaration_equals", mediaQuery: "(max-width: 700px)", selector: ".lesson-cards", property: "display", expectedValue: "block", description: "狭い画面で縦並びになる。", required: true },
    ],
    order: 6,
    difficulty: 3,
    estimatedMinutes: 22,
    hints: ["mainの中に複数sectionを置きます。", "gridとgapで縦方向のまとまりを作ります。", "カード部分だけresponsiveにします。"],
  },
];

export const htmlCssGrade2Course = createHtmlCssCourse({
  id: "course_html_css_grade_2",
  levelId: "level_html_css_2",
  title: "HTML/CSS 2級",
  description: "小さなページ部品を組み合わせ、responsiveで扱いやすいレイアウトを作るコースです。",
  chapterId,
  chapterTitle: "HTML/CSS 2級 Layout Components",
  chapterDescription: "カード、フォーム、ナビゲーション、表、部品バリエーションを組み合わせます。",
  lessons,
});
