import { commandCourse, commandEnvironment, commandFileLesson } from "../shared";

const chapterId = "chapter_command1_practical_maintenance";

export const commandGrade1Course = commandCourse({
  id: "course_command_grade_1",
  levelId: "level_command_1",
  title: "Command 1級",
  description: "実務に近い整理・修正作業を、仮想terminalだけで安全に練習する。",
  chapterId,
  chapterTitle: "Practical Maintenance",
  chapterDescription: "既存fileを読み、必要な操作だけを小さく行う。",
  lessons: [
    commandFileLesson(chapterId, {
      id: "lesson_command1_01_bug_fix_cleanup",
      slug: "bug-fix-cleanup",
      title: "Lesson 01: bug fix cleanup",
      objective: "間違った名前のfileを正しい名前へ直す。",
      taskMd: "`summery.txt` を `summary.txt` にrenameしてください。",
      starterCode: "dir",
      sampleOutput: "summary.txt",
      constraints: ["内容は変えずにfile名だけを直します。", "`move` を使います。"],
      difficulty: 3,
      estimatedMinutes: 15,
      order: 1,
      hints: ["renameも `move` で行えます。", "`move summery.txt summary.txt` と書きます。"],
      environment: commandEnvironment([{ path: "C:\\Users\\student\\summery.txt", type: "file", content: "monthly summary\n" }]),
      requirements: [
        { id: "summary-fixed", order: 1, visibility: "public", kind: "file_content_equals", path: "summary.txt", description: "summary.txt exists with the original content.", expectedContent: "monthly summary\n", required: true },
        { id: "misspelled-removed", order: 2, visibility: "hidden", kind: "file_not_exists", path: "summery.txt", description: "summery.txt is gone.", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command1_02_spec_change_release",
      slug: "spec-change-release",
      title: "Lesson 02: spec change release",
      objective: "新しいrelease directoryへ成果物を配置する。",
      taskMd: "`release` directoryを作り、`app.txt` を `release\\app.txt` にcopyしてください。",
      starterCode: "dir",
      sampleOutput: "release\\app.txt",
      constraints: ["元fileは残してください。", "release directoryが存在しない場合は作成します。"],
      difficulty: 3,
      estimatedMinutes: 15,
      order: 2,
      hints: ["`mkdir release` のあとにcopyします。"],
      environment: commandEnvironment([{ path: "C:\\Users\\student\\app.txt", type: "file", content: "version 1\n" }]),
      requirements: [
        { id: "release-app", order: 1, visibility: "public", kind: "file_content_equals", path: "release\\app.txt", description: "app.txt is copied into release.", expectedContent: "version 1\n", required: true },
        { id: "source-app-kept", order: 2, visibility: "hidden", kind: "file_content_equals", path: "app.txt", description: "app.txt remains.", expectedContent: "version 1\n", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command1_03_test_oriented_cleanup",
      slug: "test-oriented-cleanup",
      title: "Lesson 03: test-oriented cleanup",
      objective: "条件を読んで不要fileだけを削除する。",
      taskMd: "`debug.tmp` と `cache.tmp` を削除し、`readme.txt` は残してください。",
      starterCode: "dir",
      sampleOutput: "tmp files removed",
      constraints: ["`.tmp` fileだけを削除します。", "readme.txtは残します。"],
      difficulty: 3,
      estimatedMinutes: 15,
      order: 3,
      hints: ["削除は1fileずつ `del` で行います。"],
      environment: commandEnvironment([
        { path: "C:\\Users\\student\\debug.tmp", type: "file", content: "debug\n" },
        { path: "C:\\Users\\student\\cache.tmp", type: "file", content: "cache\n" },
        { path: "C:\\Users\\student\\readme.txt", type: "file", content: "keep\n" },
      ]),
      requirements: [
        { id: "debug-deleted", order: 1, visibility: "public", kind: "file_not_exists", path: "debug.tmp", description: "debug.tmp is deleted.", required: true },
        { id: "cache-deleted", order: 2, visibility: "hidden", kind: "file_not_exists", path: "cache.tmp", description: "cache.tmp is deleted.", required: true },
        { id: "readme-kept", order: 3, visibility: "hidden", kind: "file_content_equals", path: "readme.txt", description: "readme.txt remains.", expectedContent: "keep\n", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command1_04_refactor_archive",
      slug: "refactor-archive",
      title: "Lesson 04: refactor archive",
      objective: "散らばったfileをarchive directoryへ整理する。",
      taskMd: "`archive` directoryを作り、`jan.txt` と `feb.txt` をarchiveへmoveしてください。",
      starterCode: "dir",
      sampleOutput: "archive\\jan.txt\narchive\\feb.txt",
      constraints: ["move後、元の場所にjan.txt/feb.txtは残しません。", "内容は変えません。"],
      difficulty: 4,
      estimatedMinutes: 18,
      order: 4,
      hints: ["mkdirのあと、moveを2回使います。"],
      environment: commandEnvironment([
        { path: "C:\\Users\\student\\jan.txt", type: "file", content: "jan\n" },
        { path: "C:\\Users\\student\\feb.txt", type: "file", content: "feb\n" },
      ]),
      requirements: [
        { id: "jan-archived", order: 1, visibility: "public", kind: "file_content_equals", path: "archive\\jan.txt", description: "jan.txt is moved into archive.", expectedContent: "jan\n", required: true },
        { id: "feb-archived", order: 2, visibility: "hidden", kind: "file_content_equals", path: "archive\\feb.txt", description: "feb.txt is moved into archive.", expectedContent: "feb\n", required: true },
        { id: "jan-original-absent", order: 3, visibility: "hidden", kind: "file_not_exists", path: "jan.txt", description: "jan.txt is absent from the original location.", required: true },
      ],
    }),
  ],
});
