import type { Course } from "../../../domain/curriculum";

const courseId = "course_javascript_grade_2";
const chapterId = "chapter_javascript_grade_2_foundation";

export const javascriptGrade2Course: Course = {
  id: courseId,
  languageId: "lang_javascript",
  levelId: "level_javascript_2",
  title: "JavaScript 2級",
  description: "関数、class、例外、配列集計、debug、小さなprojectへ進むためのJavaScript 2級コースです。",
  curriculumVersion: "0.1.0",
  validFrom: "2026-09-05",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "JavaScript 2級 Foundation",
      description: "基礎文法を組み合わせ、少し大きい処理を関数やclassへ分けて書くChapterです。",
      order: 1,
      lessons: [
        {
          id: "lesson_js2_01_function_return",
          chapterId,
          slug: "function-return",
          title: "Lesson 01: 関数の戻り値",
          objective: "計算を関数へ切り出し、戻り値を使って結果を出力する。",
          explanationMd: "2級では、処理をただ順番に書くのではなく、名前を付けた関数へ分けて再利用できる形にします。return は関数の計算結果を呼び出し元へ返すために使います。",
          taskMd: "価格 price と割引率 rate を整数で受け取り、discountedPrice(price, rate) 関数で割引後の価格を計算して出力してください。",
          starterCode: "function discountedPrice(price, rate) {\n  return price;\n}\n\nconst price = Number(readline());\nconst rate = Number(readline());\nconsole.log(discountedPrice(price, rate));\n",
          sampleInput: "1000\n10\n",
          sampleOutput: "900\n",
          constraints: ["discountedPrice(price, rate) 関数を定義してください。", "関数の中で return を使って計算結果を返してください。", "割引後の価格は Math.floor(price * (100 - rate) / 100) で整数として計算してください。", "出力は割引後の価格を1行にしてください。"],
          difficulty: 2,
          estimatedMinutes: 12,
          order: 1,
          status: "published",
          hints: ["rate は割引率なので、支払う割合は 100 - rate です。", "return Math.floor(price * (100 - rate) / 100); と書くと整数の価格を返せます。", "入力を受け取る部分と、計算する関数を分けて考えましょう。"],
          exercises: [
            {
              id: "ex_js2_01_01",
              lessonId: "lesson_js2_01_function_return",
              type: "code",
              promptMd: "discountedPrice 関数の戻り値で割引後の価格を出力します。",
              starterCode: "function discountedPrice(price, rate) {\n  return price;\n}\n\nconst price = Number(readline());\nconst rate = Number(readline());\nconsole.log(discountedPrice(price, rate));\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の価格と割引率で、整数の割引後価格を正しく出力する。",
              testCases: [
                { id: "tc_js2_01_public", order: 1, visibility: "public", stdin: "1000\n10\n", expectedStdout: "900\n", comparator: "trimmed_text", weight: 1, required: true },
                { id: "tc_js2_01_hidden", order: 2, visibility: "hidden", stdin: "2500\n20\n", expectedStdout: "2000\n", comparator: "trimmed_text", weight: 1, required: true },
              ],
            },
          ],
        },
        {
          id: "lesson_js2_02_classes",
          chapterId,
          slug: "classes",
          title: "Lesson 02: class",
          objective: "classでデータと処理をまとめ、objectのメソッドを呼び出す。",
          explanationMd: "class は、関連するデータと処理を1つの型としてまとめるために使います。constructor でobjectの初期値を受け取り、this を通してプロパティやメソッドを扱います。",
          taskMd: "Student class を作り、name と score を受け取って保存してください。label() メソッドで `name:score` の形の文字列を返し、その結果を出力してください。",
          starterCode: "class Student {\n  constructor(name, score) {\n    this.name = name;\n    this.score = score;\n  }\n\n  label() {\n    return this.name;\n  }\n}\n\nconst name = readline();\nconst score = Number(readline());\nconst student = new Student(name, score);\nconsole.log(student.label());\n",
          sampleInput: "Aki\n82\n",
          sampleOutput: "Aki:82\n",
          constraints: ["Student class を定義してください。", "constructor(name, score) で name と score をプロパティに保存してください。", "label() メソッドで `name:score` の文字列を return してください。", "作成した student object の label() を呼び出して出力してください。"],
          difficulty: 3,
          estimatedMinutes: 15,
          order: 2,
          status: "published",
          hints: ["score は数値ですが、文字列へつなげるときは String(this.score) が使えます。", "label の return は this.name + \":\" + this.score の形にできます。", "this.name と this.score は constructor で代入したobjectごとの値です。"],
          exercises: [
            {
              id: "ex_js2_02_01",
              lessonId: "lesson_js2_02_classes",
              type: "code",
              promptMd: "Student objectのメソッドで、名前と点数をまとめた表示ラベルを返します。",
              starterCode: "class Student {\n  constructor(name, score) {\n    this.name = name;\n    this.score = score;\n  }\n\n  label() {\n    return this.name;\n  }\n}\n\nconst name = readline();\nconst score = Number(readline());\nconst student = new Student(name, score);\nconsole.log(student.label());\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の名前と点数で `name:score` の形式を正しく出力する。",
              testCases: [
                { id: "tc_js2_02_public", order: 1, visibility: "public", stdin: "Aki\n82\n", expectedStdout: "Aki:82\n", comparator: "trimmed_text", weight: 1, required: true },
                { id: "tc_js2_02_hidden", order: 2, visibility: "hidden", stdin: "Ren\n95\n", expectedStdout: "Ren:95\n", comparator: "trimmed_text", weight: 1, required: true },
              ],
            },
          ],
        },
        {
          id: "lesson_js2_03_error_handling",
          chapterId,
          slug: "error-handling",
          title: "Lesson 03: error handling",
          objective: "throwとtry/catchで入力エラーを受け止め、処理を安全に続ける。",
          explanationMd: "JavaScriptでは throw new Error(...) でエラーを発生させ、try/catch で受け止められます。入力検証を関数に分けると、正常系とエラー系を読みやすく整理できます。",
          taskMd: "1行の入力 value を受け取り、整数へ変換できる場合は `number:<整数>`、変換できない場合は `invalid` と出力してください。変換処理は parseNumber(value) と try/catch で扱ってください。",
          starterCode: "function parseNumber(value) {\n  return Number(value);\n}\n\nconst value = readline();\ntry {\n  const number = parseNumber(value);\n  console.log(number);\n} catch (error) {\n  console.log(\"error\");\n}\n",
          sampleInput: "42\n",
          sampleOutput: "number:42\n",
          constraints: ["parseNumber(value) 関数を定義してください。", "Number.isNaN(number) のときは throw new Error(\"invalid\") してください。", "try/catch で変換できない入力を受け止めてください。", "整数へ変換できない場合は `invalid` を出力してください。"],
          difficulty: 3,
          estimatedMinutes: 14,
          order: 3,
          status: "published",
          hints: ["Number(value) の結果を number に入れてから Number.isNaN(number) を確認します。", "NaN のときに throw new Error(\"invalid\"); とすると catch へ移れます。", "正常なときは console.log(\"number:\" + number)、catch 側は console.log(\"invalid\") です。"],
          exercises: [
            {
              id: "ex_js2_03_01",
              lessonId: "lesson_js2_03_error_handling",
              type: "code",
              promptMd: "try/catchで入力変換を守り、数値と不正入力を別々に出力します。",
              starterCode: "function parseNumber(value) {\n  return Number(value);\n}\n\nconst value = readline();\ntry {\n  const number = parseNumber(value);\n  console.log(number);\n} catch (error) {\n  console.log(\"error\");\n}\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "整数入力と整数ではない入力の両方で、指定されたメッセージを正しく出力する。",
              testCases: [
                { id: "tc_js2_03_public", order: 1, visibility: "public", stdin: "42\n", expectedStdout: "number:42\n", comparator: "trimmed_text", weight: 1, required: true },
                { id: "tc_js2_03_hidden", order: 2, visibility: "hidden", stdin: "oops\n", expectedStdout: "invalid\n", comparator: "trimmed_text", weight: 1, required: true },
              ],
            },
          ],
        },
        {
          id: "lesson_js2_04_array_methods",
          chapterId,
          slug: "array-methods",
          title: "Lesson 04: array methods",
          objective: "split、map、filterを使って文字列入力を配列として処理する。",
          explanationMd: "入力が1行にまとまっているときは split() で分割し、map() で数値へ変換できます。filter() を使うと条件に合う値だけを残せます。",
          taskMd: "スペース区切りの整数を受け取り、偶数だけを取り出して合計を出力してください。",
          starterCode: "const numbers = readline().split(\" \").map((value) => Number(value));\nconst evenNumbers = numbers;\nconst total = evenNumbers.reduce((sum, number) => sum + number, 0);\nconsole.log(total);\n",
          sampleInput: "1 2 3 4\n",
          sampleOutput: "6\n",
          constraints: ["split() と map() を使って数値配列を作ってください。", "filter() で偶数だけを残してください。", "reduce() またはforで偶数の合計を計算してください。", "出力は合計だけを1行にしてください。"],
          difficulty: 3,
          estimatedMinutes: 16,
          order: 4,
          status: "published",
          hints: ["偶数かどうかは number % 2 === 0 で判定できます。", "numbers.filter((number) => number % 2 === 0) で偶数だけを残せます。", "reduce((sum, number) => sum + number, 0) で合計を作れます。"],
          exercises: [
            {
              id: "ex_js2_04_01",
              lessonId: "lesson_js2_04_array_methods",
              type: "code",
              promptMd: "配列メソッドで入力を変換し、偶数だけの合計を出力します。",
              starterCode: "const numbers = readline().split(\" \").map((value) => Number(value));\nconst evenNumbers = numbers;\nconst total = evenNumbers.reduce((sum, number) => sum + number, 0);\nconsole.log(total);\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "偶数を含む入力と偶数がない入力の両方で、正しい合計を出力する。",
              testCases: [
                { id: "tc_js2_04_public", order: 1, visibility: "public", stdin: "1 2 3 4\n", expectedStdout: "6\n", comparator: "trimmed_text", weight: 1, required: true },
                { id: "tc_js2_04_hidden", order: 2, visibility: "hidden", stdin: "5 7 9\n", expectedStdout: "0\n", comparator: "trimmed_text", weight: 1, required: true },
              ],
            },
          ],
        },
        {
          id: "lesson_js2_05_algorithm_debug",
          chapterId,
          slug: "algorithm-debug",
          title: "Lesson 05: algorithm debug",
          objective: "配列を走査するアルゴリズムのバグを見つけ、正しい最大値を返す。",
          explanationMd: "アルゴリズムのdebugでは、コードがどの値を順番に見ているか、変数がいつ更新されるかを追います。最大値を探す処理では、最初の候補値と比較条件が特に重要です。",
          taskMd: "スペース区切りの整数を読み取り、highestScore(scores) 関数で最大値を返してください。starter codeにはバグがあります。負の数だけの入力でも正しい最大値を出力できるように直してください。",
          starterCode: "const scores = readline().split(\" \").map((value) => Number(value));\n\nfunction highestScore(scores) {\n  let best = 0;\n  for (const score of scores) {\n    if (score < best) {\n      best = score;\n    }\n  }\n  return best;\n}\n\nconsole.log(highestScore(scores));\n",
          sampleInput: "3 8 5\n",
          sampleOutput: "8\n",
          constraints: ["highestScore(scores) 関数を残してください。", "scores の全要素を確認して最大値を返してください。", "負の数だけの入力でも正しく動くようにしてください。", "出力は最大値だけを1行にしてください。"],
          difficulty: 4,
          estimatedMinutes: 18,
          order: 5,
          status: "published",
          hints: ["best を 0 で始めると、すべて負の数のときに存在しない0を返してしまいます。", "最初の候補は scores[0] にすると、入力にある値から比較を始められます。", "最大値を探す比較条件は、score が best より大きいときに更新します。"],
          exercises: [
            {
              id: "ex_js2_05_01",
              lessonId: "lesson_js2_05_algorithm_debug",
              type: "code",
              promptMd: "最大値探索のバグを直し、正の数でも負の数でも正しい結果を返します。",
              starterCode: "const scores = readline().split(\" \").map((value) => Number(value));\n\nfunction highestScore(scores) {\n  let best = 0;\n  for (const score of scores) {\n    if (score < best) {\n      best = score;\n    }\n  }\n  return best;\n}\n\nconsole.log(highestScore(scores));\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "通常の数列と負数だけの数列の両方で、最大値を正しく出力する。",
              testCases: [
                { id: "tc_js2_05_public", order: 1, visibility: "public", stdin: "3 8 5\n", expectedStdout: "8\n", comparator: "trimmed_text", weight: 1, required: true },
                { id: "tc_js2_05_hidden", order: 2, visibility: "hidden", stdin: "-4 -2 -9\n", expectedStdout: "-2\n", comparator: "trimmed_text", weight: 1, required: true },
              ],
            },
          ],
        },
        {
          id: "lesson_js2_06_small_project",
          chapterId,
          slug: "small-project",
          title: "Lesson 06: small project",
          objective: "関数、class、入力検証、配列処理、debugを組み合わせて小さな集計ツールを作る。",
          explanationMd: "小さなprojectでは、1つの処理だけでなく、入力の解釈、データの保持、計算、出力を分けて組み立てます。2級で扱った関数、class、エラー処理、配列処理、最大値探索を一つの流れにまとめます。",
          taskMd: "カンマ区切りのscore文字列を1行で受け取り、数値に変換できる値だけを集計してください。ScoreBook classでcount、max、avgを計算し、`count:<件数>,max:<最大値>,avg:<整数平均>` を出力してください。",
          starterCode: "class ScoreBook {\n  constructor(scores) {\n    this.scores = scores;\n  }\n\n  count() {\n    return this.scores.length;\n  }\n\n  maxScore() {\n    return 0;\n  }\n\n  average() {\n    return 0;\n  }\n}\n\nfunction parseScores(line) {\n  return line.split(\",\").map((part) => Number(part));\n}\n\nconst scores = parseScores(readline());\nconst book = new ScoreBook(scores);\nconsole.log(\"count:\" + book.count());\n",
          sampleInput: "80,90,70\n",
          sampleOutput: "count:3,max:90,avg:80\n",
          constraints: ["ScoreBook class を使って scores を保持してください。", "parseScores(line) では Number.isNaN() を使い、数値に変換できない値を無視してください。", "maxScore() は scores の最大値を返してください。", "average() は Math.floor(合計 / 件数) の整数平均を返してください。", "出力はsummaryを1行にしてください。"],
          difficulty: 5,
          estimatedMinutes: 25,
          order: 6,
          status: "published",
          hints: ["parseScores では map の後に filter((number) => !Number.isNaN(number)) を使えます。", "maxScore は Lesson 05 と同じように、最初のscoreから比較を始めると負数にも対応できます。", "summary は \"count:\" + book.count() + \",max:\" + book.maxScore() + \",avg:\" + book.average() のように組み立てられます。"],
          exercises: [
            {
              id: "ex_js2_06_01",
              lessonId: "lesson_js2_06_small_project",
              type: "code",
              promptMd: "複数の2級要素を組み合わせ、score集計summaryを出力する小さなツールを完成させます。",
              starterCode: "class ScoreBook {\n  constructor(scores) {\n    this.scores = scores;\n  }\n\n  count() {\n    return this.scores.length;\n  }\n\n  maxScore() {\n    return 0;\n  }\n\n  average() {\n    return 0;\n  }\n}\n\nfunction parseScores(line) {\n  return line.split(\",\").map((part) => Number(part));\n}\n\nconst scores = parseScores(readline());\nconst book = new ScoreBook(scores);\nconsole.log(\"count:\" + book.count());\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "通常の数値列と不正値を含む数値列の両方で、集計summaryを正しく出力する。",
              testCases: [
                { id: "tc_js2_06_public", order: 1, visibility: "public", stdin: "80,90,70\n", expectedStdout: "count:3,max:90,avg:80\n", comparator: "trimmed_text", weight: 1, required: true },
                { id: "tc_js2_06_hidden", order: 2, visibility: "hidden", stdin: "100,no,85,95\n", expectedStdout: "count:3,max:100,avg:93\n", comparator: "trimmed_text", weight: 1, required: true },
              ],
            },
          ],
        },
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
