export const routePaths = {
  home: "/",
  languages: "/languages",
  python: "/languages/python",
  pythonGrade1: "/languages/python/grade-1",
  pythonGrade1Lesson: (lessonId: string) => "/languages/python/grade-1/lessons/" + lessonId,
  pythonGrade2: "/languages/python/grade-2",
  pythonGrade2Lesson: (lessonId: string) => "/languages/python/grade-2/lessons/" + lessonId,
  pythonGrade3: "/languages/python/grade-3",
  pythonGrade3Lesson: (lessonId: string) => "/languages/python/grade-3/lessons/" + lessonId,
  pythonGrade3Challenge: (challengeId: string) => "/languages/python/grade-3/challenges/" + challengeId,
  pythonGrade3MockExam: (examId: string) => "/languages/python/grade-3/mock-exams/" + examId,
  pythonGrade3MockExamResult: (examId: string) => "/languages/python/grade-3/mock-exams/" + examId + "/result",
  javascript: "/languages/javascript",
  javascriptGrade3: "/languages/javascript/grade-3",
  javascriptGrade3Lesson: (lessonId: string) => "/languages/javascript/grade-3/lessons/" + lessonId,
  history: "/history",
  settings: "/settings",
} as const;
