export const routePaths = {
  home: "/",
  languages: "/languages",
  python: "/languages/python",
  pythonGrade1: "/languages/python/grade-1",
  pythonGrade1Lesson: (lessonId: string) => "/languages/python/grade-1/lessons/" + lessonId,
  pythonGrade2: "/languages/python/grade-2",
  pythonGrade2Lesson: (lessonId: string) => "/languages/python/grade-2/lessons/" + lessonId,
  pythonGrade3: "/languages/python/grade-3",
  pythonGrade3Lesson: (lessonId: string) => "/languages/python/grade-3/lessons/" + lessonId,
  pythonGrade3Challenge: (challengeId: string) => "/languages/python/grade-3/challenges/" + challengeId,
  pythonGrade3MockExam: (examId: string) => "/languages/python/grade-3/mock-exams/" + examId,
  pythonGrade3MockExamResult: (examId: string) => "/languages/python/grade-3/mock-exams/" + examId + "/result",
  command: "/languages/command",
  commandGrade1: "/languages/command/grade-1",
  commandGrade1Lesson: (lessonId: string) => "/languages/command/grade-1/lessons/" + lessonId,
  commandGrade2: "/languages/command/grade-2",
  commandGrade2Lesson: (lessonId: string) => "/languages/command/grade-2/lessons/" + lessonId,
  commandGrade3: "/languages/command/grade-3",
  commandGrade3Lesson: (lessonId: string) => "/languages/command/grade-3/lessons/" + lessonId,
  cpp: "/languages/cpp",
  cppGrade1: "/languages/cpp/grade-1",
  cppGrade1Lesson: (lessonId: string) => "/languages/cpp/grade-1/lessons/" + lessonId,
  cppGrade2: "/languages/cpp/grade-2",
  cppGrade2Lesson: (lessonId: string) => "/languages/cpp/grade-2/lessons/" + lessonId,
  cppGrade3: "/languages/cpp/grade-3",
  cppGrade3Lesson: (lessonId: string) => "/languages/cpp/grade-3/lessons/" + lessonId,
  java: "/languages/java",
  javaGrade1: "/languages/java/grade-1",
  javaGrade1Lesson: (lessonId: string) => "/languages/java/grade-1/lessons/" + lessonId,
  javaGrade2: "/languages/java/grade-2",
  javaGrade2Lesson: (lessonId: string) => "/languages/java/grade-2/lessons/" + lessonId,
  javaGrade3: "/languages/java/grade-3",
  javaGrade3Lesson: (lessonId: string) => "/languages/java/grade-3/lessons/" + lessonId,
  javascript: "/languages/javascript",
  javascriptGrade1: "/languages/javascript/grade-1",
  javascriptGrade1Lesson: (lessonId: string) => "/languages/javascript/grade-1/lessons/" + lessonId,
  javascriptGrade2: "/languages/javascript/grade-2",
  javascriptGrade2Lesson: (lessonId: string) => "/languages/javascript/grade-2/lessons/" + lessonId,
  javascriptGrade3: "/languages/javascript/grade-3",
  javascriptGrade3Lesson: (lessonId: string) => "/languages/javascript/grade-3/lessons/" + lessonId,
  ruby: "/languages/ruby",
  rubyGrade1: "/languages/ruby/grade-1",
  rubyGrade1Lesson: (lessonId: string) => "/languages/ruby/grade-1/lessons/" + lessonId,
  rubyGrade2: "/languages/ruby/grade-2",
  rubyGrade2Lesson: (lessonId: string) => "/languages/ruby/grade-2/lessons/" + lessonId,
  rubyGrade3: "/languages/ruby/grade-3",
  rubyGrade3Lesson: (lessonId: string) => "/languages/ruby/grade-3/lessons/" + lessonId,
  htmlCss: "/languages/html-css",
  htmlCssGrade1: "/languages/html-css/grade-1",
  htmlCssGrade1Lesson: (lessonId: string) => "/languages/html-css/grade-1/lessons/" + lessonId,
  htmlCssGrade2: "/languages/html-css/grade-2",
  htmlCssGrade2Lesson: (lessonId: string) => "/languages/html-css/grade-2/lessons/" + lessonId,
  htmlCssGrade3: "/languages/html-css/grade-3",
  htmlCssGrade3Lesson: (lessonId: string) => "/languages/html-css/grade-3/lessons/" + lessonId,
  history: "/history",
  settings: "/settings",
} as const;
