import { commandCourse, commandEnvironment, commandFileLesson } from "../shared";

const chapterId = "chapter_command2_file_management";

export const commandGrade2Course = commandCourse({
  id: "course_command_grade_2",
  levelId: "level_command_2",
  title: "Command 2級",
  description: "複数stepのfile整理を、仮想terminalで安全に練習する。",
  chapterId,
  chapterTitle: "File Management",
  chapterDescription: "backup、整理、cleanupの流れを仮想filesystemで扱う。",
  lessons: [
    commandFileLesson(chapterId, {
      id: "lesson_command2_01_backup_workflow",
      slug: "backup-workflow",
      title: "Lesson 01: backup workflow",
      objective: "copyとdirectory作成でbackupを作る。",
      taskMd: "`backup` directoryを作り、`plan.txt` を `backup\\plan.txt` にcopyしてください。",
      starterCode: "dir",
      sampleOutput: "backup\\plan.txt",
      constraints: ["`mkdir` と `copy` を使います。", "元のplan.txtは残してください。"],
      difficulty: 2,
      estimatedMinutes: 12,
      order: 1,
      hints: ["まず `mkdir backup` です。", "`copy plan.txt backup\\plan.txt` でbackupできます。"],
      environment: commandEnvironment([{ path: "C:\\Users\\student\\plan.txt", type: "file", content: "ship it\n" }]),
      requirements: [
        { id: "backup-copy", order: 1, visibility: "public", kind: "file_content_equals", path: "backup\\plan.txt", description: "backup\\plan.txt exists.", expectedContent: "ship it\n", required: true },
        { id: "plan-kept", order: 2, visibility: "hidden", kind: "file_content_equals", path: "plan.txt", description: "plan.txt remains.", expectedContent: "ship it\n", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command2_02_rename_cleanup",
      slug: "rename-cleanup",
      title: "Lesson 02: rename cleanup",
      objective: "moveでfile名を変え、不要fileを削除する。",
      taskMd: "`draft.log` を `final.log` にrenameし、`old.log` を削除してください。",
      starterCode: "dir",
      sampleOutput: "final.log",
      constraints: ["renameには `move` を使います。", "削除には `del` を使います。"],
      difficulty: 2,
      estimatedMinutes: 12,
      order: 2,
      hints: ["`move draft.log final.log` でrenameできます。", "`del old.log` で不要fileを削除します。"],
      environment: commandEnvironment([
        { path: "C:\\Users\\student\\draft.log", type: "file", content: "done\n" },
        { path: "C:\\Users\\student\\old.log", type: "file", content: "old\n" },
      ]),
      requirements: [
        { id: "final-log", order: 1, visibility: "public", kind: "file_content_equals", path: "final.log", description: "final.log exists.", expectedContent: "done\n", required: true },
        { id: "old-log-deleted", order: 2, visibility: "hidden", kind: "file_not_exists", path: "old.log", description: "old.log is deleted.", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command2_03_nested_report",
      slug: "nested-report",
      title: "Lesson 03: nested report",
      objective: "既存directory配下へfileを書き出す。",
      taskMd: "`reports\\daily.txt` に `complete` と書き込んでください。",
      starterCode: "dir reports",
      sampleOutput: "reports\\daily.txt",
      constraints: ["既存のreports directoryを使います。", "`echo` redirectionで内容を書き込みます。"],
      difficulty: 2,
      estimatedMinutes: 12,
      order: 3,
      hints: ["`echo complete > reports\\daily.txt` と書きます。"],
      environment: commandEnvironment([{ path: "C:\\Users\\student\\reports", type: "directory" }]),
      requirements: [
        { id: "daily-report", order: 1, visibility: "public", kind: "file_content_equals", path: "reports\\daily.txt", description: "daily.txt contains complete.", expectedContent: "complete\n", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command2_04_archive_move",
      slug: "archive-move",
      title: "Lesson 04: archive move",
      objective: "作業fileをarchiveへ移動する。",
      taskMd: "`result.txt` を `archive\\result.txt` へmoveしてください。",
      starterCode: "dir",
      sampleOutput: "archive\\result.txt",
      constraints: ["move後、元のresult.txtは残しません。"],
      difficulty: 2,
      estimatedMinutes: 12,
      order: 4,
      hints: ["`move result.txt archive\\result.txt` です。"],
      environment: commandEnvironment([
        { path: "C:\\Users\\student\\archive", type: "directory" },
        { path: "C:\\Users\\student\\result.txt", type: "file", content: "ok\n" },
      ]),
      requirements: [
        { id: "archived-result", order: 1, visibility: "public", kind: "file_content_equals", path: "archive\\result.txt", description: "result.txt is archived.", expectedContent: "ok\n", required: true },
        { id: "result-original-absent", order: 2, visibility: "hidden", kind: "file_not_exists", path: "result.txt", description: "result.txt is absent from the original location.", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command2_05_empty_directory_cleanup",
      slug: "empty-directory-cleanup",
      title: "Lesson 05: empty directory cleanup",
      objective: "空directoryだけを安全に削除する。",
      taskMd: "`scratch` directoryを削除し、`data` directoryは残してください。",
      starterCode: "dir",
      sampleOutput: "scratch removed",
      constraints: ["`rmdir scratch` を使います。", "data directoryは残します。"],
      difficulty: 2,
      estimatedMinutes: 12,
      order: 5,
      hints: ["空directoryはrmdirで削除できます。"],
      environment: commandEnvironment([
        { path: "C:\\Users\\student\\scratch", type: "directory" },
        { path: "C:\\Users\\student\\data", type: "directory" },
      ]),
      requirements: [
        { id: "scratch-absent", order: 1, visibility: "public", kind: "file_not_exists", path: "scratch", description: "scratch is removed.", required: true },
        { id: "data-kept", order: 2, visibility: "hidden", kind: "directory_exists", path: "data", description: "data remains.", required: true },
      ],
    }),
    commandFileLesson(chapterId, {
      id: "lesson_command2_06_small_cleanup_project",
      slug: "small-cleanup-project",
      title: "Lesson 06: small cleanup project",
      objective: "作成、copy、削除を組み合わせる。",
      taskMd: "`release` directoryを作り、`notes.txt` をcopyし、`tmp.txt` を削除してください。",
      starterCode: "dir",
      sampleOutput: "release\\notes.txt",
      constraints: ["複数行で順番にcommandを書きます。", "tmp.txtは最後に残しません。"],
      difficulty: 3,
      estimatedMinutes: 15,
      order: 6,
      hints: ["mkdir、copy、delを1行ずつ使います。"],
      environment: commandEnvironment([
        { path: "C:\\Users\\student\\notes.txt", type: "file", content: "notes\n" },
        { path: "C:\\Users\\student\\tmp.txt", type: "file", content: "tmp\n" },
      ]),
      requirements: [
        { id: "release-notes", order: 1, visibility: "public", kind: "file_content_equals", path: "release\\notes.txt", description: "notes.txt is copied into release.", expectedContent: "notes\n", required: true },
        { id: "tmp-deleted", order: 2, visibility: "hidden", kind: "file_not_exists", path: "tmp.txt", description: "tmp.txt is deleted.", required: true },
      ],
    }),
  ],
});
