import { createHtmlCssCourse, type HtmlCssLessonSeed } from "../shared";

const chapterId = "chapter_html_css_grade_3_preview";

const lessons: HtmlCssLessonSeed[] = [
  {
    id: "lesson_htmlcss3_01_split_preview",
    slug: "split-preview",
    title: "Lesson 01: split editor preview",
    objective: "HTMLとCSSを別々に編集し、previewで変更を確認する。",
    task: "index.html の見出しと説明、styles.css の色や余白を変え、previewで反映を確認してください。",
    html: "<main class=\"profile-card\">\n  <h1>Programming Trainer</h1>\n  <p>HTMLとCSSで、見出しと説明のある小さなカードを作ります。</p>\n</main>\n",
    css: ".profile-card {\n  padding: 24px;\n  border: 2px solid #176b87;\n}\n\n.profile-card h1 {\n  color: #176b87;\n}\n\n@media (max-width: 700px) {\n  .profile-card {\n    padding: 16px;\n  }\n}\n",
    domRequirements: [
      { id: "profile-card-main", order: 1, visibility: "public", kind: "selector_exists", selector: "main.profile-card", description: "mainタグに profile-card class が付いている。", required: true },
      { id: "profile-card-heading", order: 2, visibility: "public", kind: "text_includes", selector: "main.profile-card h1", expectedText: "Programming Trainer", description: "profile-card内のh1に Programming Trainer が含まれている。", required: true },
      { id: "profile-card-description", order: 3, visibility: "hidden", kind: "selector_exists", selector: "main.profile-card p", description: "profile-card内に説明文のpタグがある。", required: true },
    ],
    styleRequirements: [
      { id: "profile-card-padding", order: 4, visibility: "public", kind: "declaration_equals", selector: ".profile-card", property: "padding", expectedValue: "24px", description: "profile-card の通常時の padding が 24px である。", required: true },
      { id: "profile-card-responsive-padding", order: 5, visibility: "hidden", kind: "media_declaration_equals", mediaQuery: "(max-width: 700px)", selector: ".profile-card", property: "padding", expectedValue: "16px", description: "狭い画面向けの profile-card padding が調整されている。", required: true },
    ],
    order: 1,
    difficulty: 1,
    estimatedMinutes: 12,
    hints: ["h1 の文字を変えるとpreviewの見出しも変わります。", "color や background を変えると見た目の変化を確認できます。", "HTMLは構造、CSSは見た目、と役割を分けて考えましょう。"],
  },
  {
    id: "lesson_htmlcss3_02_heading_paragraph",
    slug: "heading-paragraph",
    title: "Lesson 02: heading and paragraph",
    objective: "見出しと段落で、読みやすい情報のまとまりを作る。",
    task: "section.profile-summary の中にh2とpを置き、CSSで見出し色と行間を整えてください。",
    html: "<section class=\"profile-summary\">\n  <h2>学習メモ</h2>\n  <p>今日学んだことを短くまとめます。</p>\n</section>\n",
    css: ".profile-summary {\n  padding: 20px;\n}\n\n.profile-summary h2 {\n  color: #176b87;\n}\n\n.profile-summary p {\n  line-height: 1.7;\n}\n",
    domRequirements: [
      { id: "summary-section", order: 1, visibility: "public", kind: "selector_exists", selector: "section.profile-summary", description: "profile-summary sectionがある。", required: true },
      { id: "summary-heading", order: 2, visibility: "public", kind: "text_includes", selector: ".profile-summary h2", expectedText: "学習メモ", description: "h2に学習メモが含まれている。", required: true },
      { id: "summary-paragraph", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".profile-summary p", description: "説明段落がある。", required: true },
    ],
    styleRequirements: [
      { id: "summary-padding", order: 4, visibility: "public", kind: "declaration_equals", selector: ".profile-summary", property: "padding", expectedValue: "20px", description: "sectionに余白がある。", required: true },
      { id: "summary-line-height", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".profile-summary p", property: "line-height", expectedValue: "1.7", description: "段落の行間が整っている。", required: true },
    ],
    order: 2,
    difficulty: 1,
    estimatedMinutes: 12,
    hints: ["sectionの中にh2とpを入れます。", "見出しだけに色を付けるには .profile-summary h2 を使います。", "line-heightで段落の読みやすさを調整できます。"],
  },
  {
    id: "lesson_htmlcss3_03_link_button",
    slug: "link-button",
    title: "Lesson 03: link button",
    objective: "aタグにclassを付けて、ボタンのようなリンクを作る。",
    task: "a.cta-link を作り、hrefとボタン風の余白・背景色を指定してください。",
    html: "<section class=\"cta-area\">\n  <h2>次のLessonへ進む</h2>\n  <a class=\"cta-link\" href=\"/languages/html-css/grade-3\">Curriculumへ戻る</a>\n</section>\n",
    css: ".cta-link {\n  display: inline-block;\n  padding: 10px 16px;\n  background: #176b87;\n  color: white;\n}\n",
    domRequirements: [
      { id: "cta-link-exists", order: 1, visibility: "public", kind: "selector_exists", selector: "a.cta-link", description: "cta-link classのリンクがある。", required: true },
      { id: "cta-link-href", order: 2, visibility: "public", kind: "attribute_equals", selector: "a.cta-link", attributeName: "href", expectedValue: "/languages/html-css/grade-3", description: "リンク先がCurriculumになっている。", required: true },
      { id: "cta-heading", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".cta-area h2", description: "リンクの前に見出しがある。", required: true },
    ],
    styleRequirements: [
      { id: "cta-display", order: 4, visibility: "public", kind: "declaration_equals", selector: ".cta-link", property: "display", expectedValue: "inline-block", description: "リンクをinline-blockにする。", required: true },
      { id: "cta-padding", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".cta-link", property: "padding", expectedValue: "10px 16px", description: "リンクにボタン風の余白がある。", required: true },
    ],
    order: 3,
    difficulty: 1,
    estimatedMinutes: 14,
    hints: ["aタグはhref属性で移動先を書きます。", "classを付けるとCSSで見た目を指定できます。", "display: inline-block にするとpaddingが効きやすくなります。"],
  },
  {
    id: "lesson_htmlcss3_04_list",
    slug: "list",
    title: "Lesson 04: list",
    objective: "ul/liで箇条書きを作り、CSSで間隔を整える。",
    task: "ul.skill-list に3つのliを置き、項目同士の余白を指定してください。",
    html: "<section class=\"skills\">\n  <h2>できること</h2>\n  <ul class=\"skill-list\">\n    <li>HTMLを書く</li>\n    <li>CSSを書く</li>\n    <li>previewで確認する</li>\n  </ul>\n</section>\n",
    css: ".skill-list {\n  padding-left: 24px;\n}\n\n.skill-list li {\n  margin-bottom: 8px;\n}\n",
    domRequirements: [
      { id: "skill-list", order: 1, visibility: "public", kind: "selector_exists", selector: "ul.skill-list", description: "skill-listのulがある。", required: true },
      { id: "skill-first-item", order: 2, visibility: "public", kind: "text_includes", selector: ".skill-list li", expectedText: "HTMLを書く", description: "最初の項目にHTMLを書くが含まれる。", required: true },
      { id: "skill-items", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".skill-list li:nth-child(3)", description: "3つ目の項目がある。", required: true },
    ],
    styleRequirements: [
      { id: "skill-padding", order: 4, visibility: "public", kind: "declaration_equals", selector: ".skill-list", property: "padding-left", expectedValue: "24px", description: "リストの左余白を指定する。", required: true },
      { id: "skill-item-gap", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".skill-list li", property: "margin-bottom", expectedValue: "8px", description: "項目の下余白がある。", required: true },
    ],
    order: 4,
    difficulty: 1,
    estimatedMinutes: 14,
    hints: ["ulの中にliを並べます。", "padding-leftでリスト全体の左余白を調整します。", "liへmargin-bottomを付けると項目が読みやすくなります。"],
  },
  {
    id: "lesson_htmlcss3_05_image_card",
    slug: "image-card",
    title: "Lesson 05: image card",
    objective: "imgタグのalt属性とCSSサイズ指定を使う。",
    task: "figure.photo-card に画像とcaptionを入れ、画像幅と角丸を指定してください。",
    html: "<figure class=\"photo-card\">\n  <img src=\"https://example.com/sample.png\" alt=\"学習画面のイメージ\">\n  <figcaption>Previewで見た目を確認します。</figcaption>\n</figure>\n",
    css: ".photo-card img {\n  width: 240px;\n  border-radius: 8px;\n}\n\n.photo-card figcaption {\n  font-size: 14px;\n}\n",
    domRequirements: [
      { id: "photo-card-image", order: 1, visibility: "public", kind: "selector_exists", selector: "figure.photo-card img", description: "figure内に画像がある。", required: true },
      { id: "photo-card-alt", order: 2, visibility: "public", kind: "attribute_equals", selector: ".photo-card img", attributeName: "alt", expectedValue: "学習画面のイメージ", description: "画像にalt属性がある。", required: true },
      { id: "photo-card-caption", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".photo-card figcaption", description: "captionがある。", required: true },
    ],
    styleRequirements: [
      { id: "photo-width", order: 4, visibility: "public", kind: "declaration_equals", selector: ".photo-card img", property: "width", expectedValue: "240px", description: "画像幅が指定されている。", required: true },
      { id: "photo-radius", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".photo-card img", property: "border-radius", expectedValue: "8px", description: "画像の角丸が指定されている。", required: true },
    ],
    order: 5,
    difficulty: 2,
    estimatedMinutes: 15,
    hints: ["imgにはsrcとaltを書きます。", "figureとfigcaptionで画像説明をまとめられます。", "border-radiusで画像の角を丸くできます。"],
  },
  {
    id: "lesson_htmlcss3_06_box_model",
    slug: "box-model",
    title: "Lesson 06: box model",
    objective: "padding、border、marginの役割を区別する。",
    task: "div.notice に内側余白、枠線、外側余白を設定してください。",
    html: "<div class=\"notice\">\n  <strong>お知らせ</strong>\n  <p>次の課題では余白を意識して配置します。</p>\n</div>\n",
    css: ".notice {\n  padding: 18px;\n  border: 1px solid #176b87;\n  margin: 16px;\n}\n",
    domRequirements: [
      { id: "notice-box", order: 1, visibility: "public", kind: "selector_exists", selector: "div.notice", description: "noticeのdivがある。", required: true },
      { id: "notice-strong", order: 2, visibility: "public", kind: "selector_exists", selector: ".notice strong", description: "強調テキストがある。", required: true },
      { id: "notice-body", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".notice p", description: "本文段落がある。", required: true },
    ],
    styleRequirements: [
      { id: "notice-padding", order: 4, visibility: "public", kind: "declaration_equals", selector: ".notice", property: "padding", expectedValue: "18px", description: "内側余白がある。", required: true },
      { id: "notice-margin", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".notice", property: "margin", expectedValue: "16px", description: "外側余白がある。", required: true },
    ],
    order: 6,
    difficulty: 2,
    estimatedMinutes: 15,
    hints: ["paddingは枠の内側の余白です。", "borderは枠線です。", "marginは外側の余白です。"],
  },
  {
    id: "lesson_htmlcss3_07_flex",
    slug: "flex",
    title: "Lesson 07: flex layout",
    objective: "display:flexで横並びの小さなナビを作る。",
    task: "nav.lesson-nav の中のリンクを横並びにし、gapで間隔を作ってください。",
    html: "<nav class=\"lesson-nav\" aria-label=\"Lesson navigation\">\n  <a href=\"#html\">HTML</a>\n  <a href=\"#css\">CSS</a>\n  <a href=\"#preview\">Preview</a>\n</nav>\n",
    css: ".lesson-nav {\n  display: flex;\n  gap: 12px;\n}\n\n.lesson-nav a {\n  color: #176b87;\n}\n",
    domRequirements: [
      { id: "lesson-nav", order: 1, visibility: "public", kind: "selector_exists", selector: "nav.lesson-nav", description: "lesson-navのnavがある。", required: true },
      { id: "lesson-nav-link", order: 2, visibility: "public", kind: "text_includes", selector: ".lesson-nav a", expectedText: "HTML", description: "HTMLリンクがある。", required: true },
      { id: "lesson-nav-third", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".lesson-nav a:nth-child(3)", description: "3つ目のリンクがある。", required: true },
    ],
    styleRequirements: [
      { id: "lesson-nav-flex", order: 4, visibility: "public", kind: "declaration_equals", selector: ".lesson-nav", property: "display", expectedValue: "flex", description: "navをflexにする。", required: true },
      { id: "lesson-nav-gap", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".lesson-nav", property: "gap", expectedValue: "12px", description: "リンク間にgapがある。", required: true },
    ],
    order: 7,
    difficulty: 2,
    estimatedMinutes: 16,
    hints: ["親要素にdisplay:flexを指定します。", "gapで子要素同士の間隔を作れます。", "navにはaria-labelを付けると目的が伝わりやすくなります。"],
  },
  {
    id: "lesson_htmlcss3_08_form",
    slug: "form",
    title: "Lesson 08: form basics",
    objective: "labelとinputを関連付けたフォームを作る。",
    task: "labelとinputを使って、名前入力欄を持つformを作ってください。",
    html: "<form class=\"signup-form\">\n  <label for=\"learner-name\">名前</label>\n  <input id=\"learner-name\" name=\"learnerName\" type=\"text\">\n</form>\n",
    css: ".signup-form {\n  display: grid;\n  gap: 8px;\n}\n\n.signup-form input {\n  padding: 10px;\n}\n",
    domRequirements: [
      { id: "signup-form", order: 1, visibility: "public", kind: "selector_exists", selector: "form.signup-form", description: "signup-formがある。", required: true },
      { id: "signup-label-for", order: 2, visibility: "public", kind: "attribute_equals", selector: ".signup-form label", attributeName: "for", expectedValue: "learner-name", description: "labelがinputと関連している。", required: true },
      { id: "signup-input-type", order: 3, visibility: "hidden", kind: "attribute_equals", selector: ".signup-form input", attributeName: "type", expectedValue: "text", description: "文字入力欄になっている。", required: true },
    ],
    styleRequirements: [
      { id: "signup-grid", order: 4, visibility: "public", kind: "declaration_equals", selector: ".signup-form", property: "display", expectedValue: "grid", description: "フォームをgridで並べる。", required: true },
      { id: "signup-gap", order: 5, visibility: "hidden", kind: "declaration_equals", selector: ".signup-form", property: "gap", expectedValue: "8px", description: "フォーム要素に間隔がある。", required: true },
    ],
    order: 8,
    difficulty: 2,
    estimatedMinutes: 16,
    hints: ["labelのforとinputのidを同じ値にします。", "formの中に入力項目をまとめます。", "gridとgapで縦方向の間隔を整えられます。"],
  },
  {
    id: "lesson_htmlcss3_09_responsive",
    slug: "responsive",
    title: "Lesson 09: responsive rule",
    objective: "media queryで狭い画面向けのスタイルを書く。",
    task: "dashboard-listを通常は横並び、狭い画面では縦並びになるようにしてください。",
    html: "<section class=\"dashboard-list\">\n  <article>HTML</article>\n  <article>CSS</article>\n</section>\n",
    css: ".dashboard-list {\n  display: flex;\n  gap: 12px;\n}\n\n@media (max-width: 700px) {\n  .dashboard-list {\n    display: block;\n  }\n}\n",
    domRequirements: [
      { id: "dashboard-list", order: 1, visibility: "public", kind: "selector_exists", selector: "section.dashboard-list", description: "dashboard-list sectionがある。", required: true },
      { id: "dashboard-card", order: 2, visibility: "public", kind: "selector_exists", selector: ".dashboard-list article", description: "article項目がある。", required: true },
      { id: "dashboard-second-card", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".dashboard-list article:nth-child(2)", description: "2つ目のarticleがある。", required: true },
    ],
    styleRequirements: [
      { id: "dashboard-flex", order: 4, visibility: "public", kind: "declaration_equals", selector: ".dashboard-list", property: "display", expectedValue: "flex", description: "通常時は横並びにする。", required: true },
      { id: "dashboard-responsive-block", order: 5, visibility: "hidden", kind: "media_declaration_equals", mediaQuery: "(max-width: 700px)", selector: ".dashboard-list", property: "display", expectedValue: "block", description: "狭い画面では縦並びへ戻す。", required: true },
    ],
    order: 9,
    difficulty: 2,
    estimatedMinutes: 18,
    hints: ["通常時の指定を先に書きます。", "@media (max-width: 700px) の中に狭い画面用の上書きを書きます。", "display:blockに戻すと縦に並びます。"],
  },
  {
    id: "lesson_htmlcss3_10_semantic_landing",
    slug: "semantic-landing",
    title: "Lesson 10: semantic landing",
    objective: "header、main、footerで小さなページを意味ごとに分ける。",
    task: "landing-pageの中にheader、main、footerを置き、heroの余白とresponsive余白を設定してください。",
    html: "<div class=\"landing-page\">\n  <header><h1>HTML/CSS Roadmap</h1></header>\n  <main class=\"hero\"><p>構造と見た目を組み合わせてページを作ります。</p></main>\n  <footer>Programming Trainer</footer>\n</div>\n",
    css: ".hero {\n  padding: 32px;\n}\n\n.landing-page footer {\n  color: #334155;\n}\n\n@media (max-width: 700px) {\n  .hero {\n    padding: 20px;\n  }\n}\n",
    domRequirements: [
      { id: "landing-header", order: 1, visibility: "public", kind: "selector_exists", selector: ".landing-page header", description: "headerがある。", required: true },
      { id: "landing-main", order: 2, visibility: "public", kind: "selector_exists", selector: ".landing-page main.hero", description: "main.heroがある。", required: true },
      { id: "landing-footer", order: 3, visibility: "hidden", kind: "selector_exists", selector: ".landing-page footer", description: "footerがある。", required: true },
    ],
    styleRequirements: [
      { id: "landing-hero-padding", order: 4, visibility: "public", kind: "declaration_equals", selector: ".hero", property: "padding", expectedValue: "32px", description: "heroに余白がある。", required: true },
      { id: "landing-responsive-padding", order: 5, visibility: "hidden", kind: "media_declaration_equals", mediaQuery: "(max-width: 700px)", selector: ".hero", property: "padding", expectedValue: "20px", description: "狭い画面向け余白がある。", required: true },
    ],
    order: 10,
    difficulty: 2,
    estimatedMinutes: 20,
    hints: ["header/main/footerでページの役割を分けます。", "mainにclassを付けるとheroだけをCSSで指定できます。", "media queryで小さい画面の余白を調整します。"],
  },
];

export const htmlCssGrade3Course = createHtmlCssCourse({
  id: "course_html_css_grade_3_foundation",
  levelId: "level_html_css_3",
  title: "HTML/CSS 3級",
  description: "HTML構造とCSSスタイルを分けて編集し、previewで見た目を確かめる基礎コースです。",
  chapterId,
  chapterTitle: "HTML/CSS 3級 Preview Foundation",
  chapterDescription: "split editorでHTMLとCSSを編集し、sandbox previewへ反映するChapterです。",
  lessons,
});
