import type { Course } from "../../../domain/curriculum";

const starterCode = "def normalize_name(name):\n    return name\n\n\ndef build_greeting(name):\n    normalized = normalize_name(name)\n    return \"Hello, \" + name\n\nname = input()\nprint(build_greeting(name))\n";

const specificationChangeStarterCode = "def shipping_fee(total):\n    return 500\n\n\ndef order_total(total):\n    return total + shipping_fee(total)\n\ntotal = int(input())\nprint(order_total(total))\n";

const testOrientedStarterCode = "def parse_scores(line):\n    return [int(part) for part in line.split(\",\")]\n\n\ndef passed_count(scores):\n    return len(scores)\n\nline = input()\nscores = parse_scores(line)\nprint(passed_count(scores))\n";

const refactoringStarterCode = "name1 = input()\nscore1 = int(input())\nname2 = input()\nscore2 = int(input())\n\nif score1 >= 80:\n    print(name1 + \":A\")\nelse:\n    print(name1 + \":B\")\n\nif score2 >= 80:\n    print(name2 + \":A\")\nelse:\n    print(name2 + \":B\")\n";

const courseId = "course_python_grade_1";

export const pythonGrade1Course: Course = {
  id: courseId,
  languageId: "lang_python",
  levelId: "level_python_1",
  title: "Python 1級",
  description: "既存コード修正、仕様変更、テスト志向、refactoringを扱うPython 1級コースです。",
  curriculumVersion: "0.1.0",
  validFrom: "2026-09-05",
  chapters: [
    {
      id: "chapter_python_grade_1_practical",
      courseId,
      title: "Python 1級 Practical Maintenance",
      description: "実務に近い既存コードの修正から始めるChapterです。",
      order: 1,
      lessons: [
        {
          id: "lesson_py1_01_bug_fix",
          chapterId: "chapter_python_grade_1_practical",
          slug: "bug-fix",
          title: "Lesson 01: bug fix",
          objective: "既存コードの意図を読み、入力の空白と表示名のbugを修正する。",
          explanationMd: "1級では、0から書くだけでなく、すでにあるコードを読み、仕様と実装のずれを小さく直します。今回のbugは、名前の前後の空白を取り除いた値を作っているのに、出力では元の値を使ってしまう点です。",
          taskMd: "normalize_name(name) は前後の空白を取り除いた名前を返してください。build_greeting(name) はnormalize後の名前を使い、`Hello, <name>` を返してください。",
          starterCode,
          sampleInput: "  Aki  \n",
          sampleOutput: "Hello, Aki\n",
          constraints: [
            "normalize_name(name) 関数を残してください。",
            "strip() を使って名前の前後の空白を取り除いてください。",
            "build_greeting(name) はnormalizeされた値を使ってください。",
            "出力は greeting 1行だけにしてください。",
          ],
          difficulty: 4,
          estimatedMinutes: 18,
          order: 1,
          status: "published",
          hints: [
            "name.strip() は文字列の前後にある空白を取り除きます。",
            "build_greeting の中では normalized という変数がすでに作られています。",
            "return \"Hello, \" + normalized のように、修正済みの値を返しましょう。",
          ],
          exercises: [
            {
              id: "ex_py1_01_01",
              lessonId: "lesson_py1_01_bug_fix",
              type: "code",
              promptMd: "既存コードを読み、名前の正規化結果をgreetingへ反映するbugを修正します。",
              starterCode,
              project: {
                entryFilePath: "main.py",
                files: [
                  {
                    path: "main.py",
                    language: "python",
                    content: starterCode,
                    editable: true,
                    purpose: "entry",
                  },
                  {
                    path: "tests/test_greeting.py",
                    language: "python",
                    content: "assert normalize_name('  Aki  ') == 'Aki'\nassert build_greeting(' Mika ') == 'Hello, Mika'\n",
                    editable: false,
                    purpose: "test",
                  },
                ],
              },
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "前後に空白がある名前でも、空白を取り除いたgreetingを出力する。",
              testCases: [
                {
                  id: "tc_py1_01_public",
                  order: 1,
                  visibility: "public",
                  stdin: "  Aki  \n",
                  expectedStdout: "Hello, Aki\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_01_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "\tRen \n",
                  expectedStdout: "Hello, Ren\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py1_02_specification_change",
          chapterId: "chapter_python_grade_1_practical",
          slug: "specification-change",
          title: "Lesson 02: specification change",
          objective: "既存の注文計算へ新しい送料仕様を追加し、古い動作も保つ。",
          explanationMd: "仕様変更では、今ある動きを壊さずに新しい条件を足します。今回は、これまで全注文に送料500円を足していた処理へ、注文金額が5000円以上なら送料を0円にする新仕様を追加します。",
          taskMd: "shipping_fee(total) を変更し、total が5000以上なら0、それ以外なら500を返してください。order_total(total) は shipping_fee(total) を使い、注文金額と送料を足した合計を返してください。",
          starterCode: specificationChangeStarterCode,
          sampleInput: "6000\n",
          sampleOutput: "6000\n",
          constraints: [
            "shipping_fee(total) 関数を残してください。",
            "total が5000以上の場合は送料0円にしてください。",
            "total が5000未満の場合はこれまで通り送料500円にしてください。",
            "order_total(total) は shipping_fee(total) を呼び出して合計を計算してください。",
          ],
          difficulty: 4,
          estimatedMinutes: 18,
          order: 2,
          status: "published",
          hints: [
            "条件分岐は if total >= 5000: の形で書けます。",
            "送料だけを shipping_fee で決めると、order_total の役割を小さく保てます。",
            "古い仕様の500円送料も残すため、else 側では return 500 にしましょう。",
          ],
          exercises: [
            {
              id: "ex_py1_02_01",
              lessonId: "lesson_py1_02_specification_change",
              type: "code",
              promptMd: "既存の注文合計計算へ、5000円以上送料無料という仕様変更を追加します。",
              starterCode: specificationChangeStarterCode,
              project: {
                entryFilePath: "main.py",
                files: [
                  {
                    path: "main.py",
                    language: "python",
                    content: specificationChangeStarterCode,
                    editable: true,
                    purpose: "entry",
                  },
                  {
                    path: "tests/test_order_total.py",
                    language: "python",
                    content: "assert shipping_fee(1200) == 500\nassert shipping_fee(7000) == 0\nassert order_total(7000) == 7000\n",
                    editable: false,
                    purpose: "test",
                  },
                ],
              },
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "5000円未満と5000円以上の注文で、新しい送料仕様に沿った合計を出力する。",
              testCases: [
                {
                  id: "tc_py1_02_public_free_shipping",
                  order: 1,
                  visibility: "public",
                  stdin: "6000\n",
                  expectedStdout: "6000\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_02_public_standard_shipping",
                  order: 2,
                  visibility: "public",
                  stdin: "1200\n",
                  expectedStdout: "1700\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_02_hidden_free_shipping",
                  order: 3,
                  visibility: "hidden",
                  stdin: "5100\n",
                  expectedStdout: "5100\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py1_03_test_oriented",
          chapterId: "chapter_python_grade_1_practical",
          slug: "test-oriented",
          title: "Lesson 03: test-oriented task",
          objective: "公開されているテストを読み、期待される振る舞いから実装を直す。",
          explanationMd: "テスト志向のtaskでは、説明文だけでなくテストコードも仕様の一部として読みます。テストが示す入力、境界値、期待値を手がかりに、関数の責務を小さく保ちながら実装を直します。",
          taskMd: "tests/test_scores.py の期待を満たすように、parse_scores(line) と passed_count(scores) を修正してください。カンマ区切りの点数から整数だけを読み取り、70点以上の点数の個数を出力します。",
          starterCode: testOrientedStarterCode,
          sampleInput: "80,65,90\n",
          sampleOutput: "2\n",
          constraints: [
            "parse_scores(line) 関数を残してください。",
            "整数へ変換できない値は無視してください。",
            "passed_count(scores) は70点以上の点数だけを数えてください。",
            "出力は合格点数の個数を1行にしてください。",
          ],
          difficulty: 4,
          estimatedMinutes: 20,
          order: 3,
          status: "published",
          hints: [
            "for part in line.split(\",\") でカンマ区切りの値を1つずつ見られます。",
            "int(part) は数値ではない文字列で ValueError になるので、try/except で無視できます。",
            "passed_count では if score >= 70: のときだけ count を増やしましょう。",
          ],
          exercises: [
            {
              id: "ex_py1_03_01",
              lessonId: "lesson_py1_03_test_oriented",
              type: "code",
              promptMd: "表示されているテストを読み、点数集計の期待動作を満たすように既存コードを修正します。",
              starterCode: testOrientedStarterCode,
              project: {
                entryFilePath: "main.py",
                files: [
                  {
                    path: "main.py",
                    language: "python",
                    content: testOrientedStarterCode,
                    editable: true,
                    purpose: "entry",
                  },
                  {
                    path: "tests/test_scores.py",
                    language: "python",
                    content: "assert parse_scores('80,65,90') == [80, 65, 90]\nassert passed_count([80, 65, 90]) == 2\nassert passed_count([70, 69, 71]) == 2\n",
                    editable: false,
                    purpose: "test",
                  },
                ],
              },
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "有効な整数だけを点数として扱い、70点以上の件数を正しく出力する。",
              testCases: [
                {
                  id: "tc_py1_03_public_mixed_scores",
                  order: 1,
                  visibility: "public",
                  stdin: "80,65,90\n",
                  expectedStdout: "2\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_03_public_boundary",
                  order: 2,
                  visibility: "public",
                  stdin: "70,69,71\n",
                  expectedStdout: "2\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_03_hidden_invalid_values",
                  order: 3,
                  visibility: "hidden",
                  stdin: "100,no,40,75\n",
                  expectedStdout: "2\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
        {
          id: "lesson_py1_04_refactoring",
          chapterId: "chapter_python_grade_1_practical",
          slug: "refactoring",
          title: "Lesson 04: refactoring",
          objective: "重複した判定処理を関数へ切り出し、外から見える出力を保つ。",
          explanationMd: "refactoring は、動きを変えずにコードの形を良くする作業です。重複している条件分岐を関数へ切り出すと、仕様変更やテスト追加に強いコードになります。",
          taskMd: "2人分の成績ラベル出力を、label_grade(name, score) 関数へ切り出してください。score が80以上なら `name:A`、それ以外なら `name:B` を返し、最終的な2行の出力は元の仕様と同じにしてください。",
          starterCode: refactoringStarterCode,
          sampleInput: "Aki\n82\nRen\n71\n",
          sampleOutput: "Aki:A\nRen:B\n",
          constraints: [
            "label_grade(name, score) 関数を定義してください。",
            "label_grade は文字列を return してください。",
            "80点以上は A、それ以外は B としてください。",
            "print は2人分の結果を1行ずつ出力してください。",
          ],
          difficulty: 4,
          estimatedMinutes: 18,
          order: 4,
          status: "published",
          hints: [
            "まず score >= 80 の条件分岐を関数の中へ移します。",
            "関数は print ではなく return name + \":A\" のように文字列を返すと使い回しやすくなります。",
            "最後は print(label_grade(name1, score1)) と print(label_grade(name2, score2)) の2回にできます。",
          ],
          exercises: [
            {
              id: "ex_py1_04_01",
              lessonId: "lesson_py1_04_refactoring",
              type: "code",
              promptMd: "重複した成績ラベル処理を関数へ切り出し、同じ出力を保つようにrefactoringします。",
              starterCode: refactoringStarterCode,
              project: {
                entryFilePath: "main.py",
                files: [
                  {
                    path: "main.py",
                    language: "python",
                    content: refactoringStarterCode,
                    editable: true,
                    purpose: "entry",
                  },
                  {
                    path: "tests/test_label_grade.py",
                    language: "python",
                    content: "assert label_grade('Aki', 82) == 'Aki:A'\nassert label_grade('Ren', 71) == 'Ren:B'\nassert label_grade('Mio', 80) == 'Mio:A'\n",
                    editable: false,
                    purpose: "test",
                  },
                ],
              },
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "重複を関数へ切り出した上で、複数の名前と点数に対して同じラベル出力を保つ。",
              testCases: [
                {
                  id: "tc_py1_04_public_basic",
                  order: 1,
                  visibility: "public",
                  stdin: "Aki\n82\nRen\n71\n",
                  expectedStdout: "Aki:A\nRen:B\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_04_public_boundary",
                  order: 2,
                  visibility: "public",
                  stdin: "Mio\n80\nKen\n79\n",
                  expectedStdout: "Mio:A\nKen:B\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py1_04_hidden_names",
                  order: 3,
                  visibility: "hidden",
                  stdin: "Nia\n95\nKai\n60\n",
                  expectedStdout: "Nia:A\nKai:B\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
