import type { Course } from "../../../domain/curriculum";
import { cppLesson } from "../shared";

const courseId = "course_cpp_grade_3_foundation";
const chapterId = "chapter_cpp3_basic";

const coutStarter = '#include <iostream>\n\nint main() {\n  std::cout << "Hello" << std::endl;\n  return 0;\n}\n';
const variableStarter = '#include <iostream>\n#include <string>\n\nint main() {\n  std::string language = "";\n  std::cout << language << std::endl;\n  return 0;\n}\n';
const inputStarter = '#include <iostream>\n#include <string>\n\nint main() {\n  std::string name;\n  std::cin >> name;\n  std::cout << "Hello " << name << std::endl;\n  return 0;\n}\n';
const operatorsStarter = '#include <iostream>\n\nint main() {\n  int a;\n  int b;\n  std::cin >> a >> b;\n  std::cout << a << std::endl;\n  std::cout << b << std::endl;\n  return 0;\n}\n';
const ifStarter = '#include <iostream>\n\nint main() {\n  int score;\n  std::cin >> score;\n  if (score >= 60) {\n    std::cout << "OK" << std::endl;\n  } else {\n    std::cout << "NG" << std::endl;\n  }\n  return 0;\n}\n';
const forStarter = '#include <iostream>\n\nint main() {\n  int n;\n  std::cin >> n;\n  for (int i = 0; i < n; i++) {\n    std::cout << i << std::endl;\n  }\n  return 0;\n}\n';
const whileStarter = '#include <iostream>\n\nint main() {\n  int n;\n  std::cin >> n;\n  while (n > 0) {\n    std::cout << n << std::endl;\n  }\n  return 0;\n}\n';
const arrayStarter = '#include <iostream>\n#include <string>\n\nint main() {\n  std::string first;\n  std::string second;\n  std::string third;\n  std::cin >> first >> second >> third;\n  std::string items[3] = {first, second, third};\n  items[1] = "?";\n  std::cout << items[0] << std::endl;\n  std::cout << items[1] << std::endl;\n  std::cout << items[2] << std::endl;\n  return 0;\n}\n';
const stringStarter = '#include <iostream>\n#include <string>\n\nint main() {\n  std::string word;\n  std::cin >> word;\n  std::cout << word << std::endl;\n  return 0;\n}\n';
const doubleStarter = '#include <iostream>\n\nint doubleNumber(int number) {\n  return number;\n}\n\nint main() {\n  int value;\n  std::cin >> value;\n  std::cout << doubleNumber(value) << std::endl;\n  return 0;\n}\n';
const tripleStarter = '#include <iostream>\n\nint tripleNumber(int number) {\n  return number;\n}\n\nint main() {\n  int value;\n  std::cin >> value;\n  std::cout << tripleNumber(value) << std::endl;\n  return 0;\n}\n';

export const cppGrade3Course: Course = {
  id: courseId,
  languageId: "lang_cpp",
  levelId: "level_cpp_3",
  title: "C++ 3級",
  description: "C++の基礎をブラウザ上で実行・採点しながら学びます。",
  curriculumVersion: "cpp-grade-3-v0.1.0",
  validFrom: "2026-09-05",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "C++ 3級 基礎",
      description: "出力、変数、入力、条件分岐、くり返し、配列、文字列、関数を練習します。",
      order: 1,
      lessons: [
        cppLesson(chapterId, {
          id: "lesson_cpp3_01_cout",
          slug: "cout",
          title: "Lesson 01: cout / 出力",
          objective: "std::coutで指定された文字を標準出力へ表示できる。",
          explanationMd: "C++ではstd::coutとstd::endlを使うと、値を1行で出力できます。",
          taskMd: "std::coutを使って Hello, Programming Trainer! と1行で出力してください。",
          starterCode: coutStarter,
          sampleInput: "",
          sampleOutput: "Hello, Programming Trainer!\n",
          constraints: ["int main()を残してください。", "出力は1行だけにしてください。", "大文字・小文字、記号、空白も一致させてください。"],
          difficulty: 1,
          estimatedMinutes: 10,
          order: 1,
          hints: ["文字列はダブルクォートで囲みます。", "std::cout << \"Hello, Programming Trainer!\" << std::endl; の形を思い出しましょう。"],
          exercises: [{ id: "ex_cpp3_01_01", promptMd: "指定された文字列を出力します。", starterCode: coutStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で期待出力と一致する。", testCases: [{ id: "tc_cpp3_01_public", order: 1, visibility: "public", stdin: "", expectedStdout: "Hello, Programming Trainer!\n" }, { id: "tc_cpp3_01_hidden_exact", order: 2, visibility: "hidden", stdin: "", expectedStdout: "Hello, Programming Trainer!\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_02_variables",
          slug: "variables",
          title: "Lesson 02: 変数",
          objective: "std::string変数に値を入れ、その値を出力できる。",
          explanationMd: "変数は値に名前を付けて保存する仕組みです。std::string language = \"C++\"; のように書きます。",
          taskMd: "変数 language に C++ を代入し、std::coutで出力してください。",
          starterCode: variableStarter,
          sampleInput: "",
          sampleOutput: "C++\n",
          constraints: ["変数名は language を使ってください。", "std::coutには変数 language を渡してください。"],
          difficulty: 1,
          estimatedMinutes: 12,
          order: 2,
          hints: ["std::string language = \"C++\"; と書きます。", "文字列を直接出すのではなく、変数を出力しましょう。"],
          exercises: [{ id: "ex_cpp3_02_01", promptMd: "変数に値を代入し、その変数を出力します。", starterCode: variableStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方に合格する。", testCases: [{ id: "tc_cpp3_02_public", order: 1, visibility: "public", stdin: "", expectedStdout: "C++\n" }, { id: "tc_cpp3_02_hidden_lines", order: 2, visibility: "hidden", stdin: "", expectedStdout: "C++\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_03_input",
          slug: "input",
          title: "Lesson 03: cin / 入力",
          objective: "std::cinで受け取った文字列を使って出力できる。",
          explanationMd: "Programming TrainerのC++実行環境では、std::cinで標準入力の値を受け取れます。",
          taskMd: "std::cinで名前を受け取り、Hello の後ろに名前を続けて出力してください。",
          starterCode: inputStarter,
          sampleInput: "Yosuke\n",
          sampleOutput: "Hello Yosuke\n",
          constraints: ["std::cinを使って入力を受け取ってください。", "Hello と入力値の間に空白を1つ入れてください。"],
          difficulty: 1,
          estimatedMinutes: 15,
          order: 3,
          hints: ["std::string name; を用意します。", "std::cin >> name; のあと、\"Hello \"とnameを出力します。"],
          exercises: [{ id: "ex_cpp3_03_01", promptMd: "標準入力から名前を受け取り、あいさつを出力します。", starterCode: inputStarter, completionCriteria: "複数の入力値で正しいあいさつを出力する。", testCases: [{ id: "tc_cpp3_03_public", order: 1, visibility: "public", stdin: "Yosuke\n", expectedStdout: "Hello Yosuke\n" }, { id: "tc_cpp3_03_hidden", order: 2, visibility: "hidden", stdin: "Mika\n", expectedStdout: "Hello Mika\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_04_types_operators",
          slug: "types-operators",
          title: "Lesson 04: 型と演算子",
          objective: "std::cinで受け取った整数を使い、算術演算子で計算できる。",
          explanationMd: "intは整数を扱う型です。+ は足し算、* はかけ算に使います。",
          taskMd: "2つの整数を受け取り、1行目に合計、2行目に積を出力してください。",
          starterCode: operatorsStarter,
          sampleInput: "3 4\n",
          sampleOutput: "7\n12\n",
          constraints: ["std::cinで整数を2つ受け取ってください。", "合計、積の順に1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 4,
          hints: ["合計は a + b、積は a * b で求められます。", "std::coutを2回使って、別々の行に出力します。"],
          exercises: [{ id: "ex_cpp3_04_01", promptMd: "2つの整数を受け取り、合計と積を計算して出力します。", starterCode: operatorsStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、合計と積を正しい順序で出力する。", testCases: [{ id: "tc_cpp3_04_public", order: 1, visibility: "public", stdin: "3 4\n", expectedStdout: "7\n12\n" }, { id: "tc_cpp3_04_hidden", order: 2, visibility: "hidden", stdin: "8 5\n", expectedStdout: "13\n40\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_05_if",
          slug: "if",
          title: "Lesson 05: if",
          objective: "ifとelseを使い、条件に応じて違う処理を実行できる。",
          explanationMd: "ifは条件が成り立つときだけ波かっこの中の処理を実行します。",
          taskMd: "整数の点数を1つ受け取り、60以上なら pass、60未満なら retry と出力してください。",
          starterCode: ifStarter,
          sampleInput: "72\n",
          sampleOutput: "pass\n",
          constraints: ["std::cinで整数を1つ受け取ってください。", "ifとelseを使って分岐してください。", "出力は pass または retry のどちらか1行にしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 5,
          hints: ["60以上かどうかは score >= 60 で判定できます。", "else側にはretryの出力を書きます。"],
          exercises: [{ id: "ex_cpp3_05_01", promptMd: "点数を受け取り、合格か再挑戦かを条件分岐で出力します。", starterCode: ifStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、点数に応じた文字列を出力する。", testCases: [{ id: "tc_cpp3_05_public_pass", order: 1, visibility: "public", stdin: "72\n", expectedStdout: "pass\n" }, { id: "tc_cpp3_05_hidden_retry", order: 2, visibility: "hidden", stdin: "45\n", expectedStdout: "retry\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_06_for",
          slug: "for",
          title: "Lesson 06: for",
          objective: "forを使い、決まった回数だけ処理をくり返せる。",
          explanationMd: "forは同じ処理をくり返すときに使います。int i = 1で始め、i <= nの間くり返します。",
          taskMd: "整数 n を1つ受け取り、1から n までの整数を1行ずつ出力してください。",
          starterCode: forStarter,
          sampleInput: "3\n",
          sampleOutput: "1\n2\n3\n",
          constraints: ["std::cinで整数を1つ受け取ってください。", "forを使ってくり返してください。", "1から入力値までを昇順で1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 6,
          hints: ["i = 0で始めると0から出力されます。", "for (int i = 1; i <= n; i++) の中で出力します。"],
          exercises: [{ id: "ex_cpp3_06_01", promptMd: "入力された数まで、forで数を順番に出力します。", starterCode: forStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、1から入力値までを正しく出力する。", testCases: [{ id: "tc_cpp3_06_public_three", order: 1, visibility: "public", stdin: "3\n", expectedStdout: "1\n2\n3\n" }, { id: "tc_cpp3_06_hidden_five", order: 2, visibility: "hidden", stdin: "5\n", expectedStdout: "1\n2\n3\n4\n5\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_07_while",
          slug: "while",
          title: "Lesson 07: while",
          objective: "whileを使い、条件が成り立つ間だけ処理をくり返せる。",
          explanationMd: "whileは条件がtrueの間、波かっこの中の処理をくり返します。",
          taskMd: "整数 n を1つ受け取り、n から1までの整数を1行ずつカウントダウンしてください。",
          starterCode: whileStarter,
          sampleInput: "3\n",
          sampleOutput: "3\n2\n1\n",
          constraints: ["std::cinで整数を1つ受け取ってください。", "whileを使ってくり返してください。", "ループの中で n を1ずつ減らしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 7,
          hints: ["while (n > 0) と書くと、nが1以上の間くり返せます。", "出力のあとに n = n - 1; を書くと、次の回で値が小さくなります。"],
          exercises: [{ id: "ex_cpp3_07_01", promptMd: "whileで入力値から1までのカウントダウンを出力します。", starterCode: whileStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値から1までを正しく出力する。", testCases: [{ id: "tc_cpp3_07_public_three", order: 1, visibility: "public", stdin: "3\n", expectedStdout: "3\n2\n1\n" }, { id: "tc_cpp3_07_hidden_five", order: 2, visibility: "hidden", stdin: "5\n", expectedStdout: "5\n4\n3\n2\n1\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_08_array",
          slug: "array",
          title: "Lesson 08: array",
          objective: "配列を作り、インデックスで値を読み書きできる。",
          explanationMd: "配列は複数の値を順番にまとめる型です。items[0]は最初の値、items[1]は2番目の値を表します。",
          taskMd: "3つの文字列を受け取って配列に入れ、2番目の値を C++ に変更してから、3つの値を1行ずつ出力してください。",
          starterCode: arrayStarter,
          sampleInput: "red blue green\n",
          sampleOutput: "red\nC++\ngreen\n",
          constraints: ["std::cinで3つの文字列を受け取ってください。", "3つの値を配列に入れてください。", "2番目の要素は items[1] で更新してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 8,
          hints: ["std::string items[3] = {...}; の形で配列を作れます。", "配列の2番目はitems[1]です。", "items[1] = \"C++\"; と書くと2番目の値を変更できます。"],
          exercises: [{ id: "ex_cpp3_08_01", promptMd: "配列の要素をインデックスで更新し、順番に出力します。", starterCode: arrayStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、2番目だけをC++に変えた3行を出力する。", testCases: [{ id: "tc_cpp3_08_public_colors", order: 1, visibility: "public", stdin: "red blue green\n", expectedStdout: "red\nC++\ngreen\n" }, { id: "tc_cpp3_08_hidden_words", order: 2, visibility: "hidden", stdin: "cat dog eel\n", expectedStdout: "cat\nC++\neel\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_09_string",
          slug: "string",
          title: "Lesson 09: string",
          objective: "std::stringを使って文字列を組み立てられる。",
          explanationMd: "std::stringは文字列を扱う型です。+ を使うと短い文字列をつなげられます。",
          taskMd: "1つの単語を受け取り、C++: の後ろにその単語を続けて出力してください。",
          starterCode: stringStarter,
          sampleInput: "runner\n",
          sampleOutput: "C++:runner\n",
          constraints: ["std::cinで1つの単語を受け取ってください。", "C++: と入力値をつなげてください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 9,
          hints: ["std::string word; を用意します。", "\"C++:\" と word を続けて出力します。"],
          exercises: [{ id: "ex_cpp3_09_01", promptMd: "文字列を受け取り、接頭辞を付けて出力します。", starterCode: stringStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、加工後の文字列を出力する。", testCases: [{ id: "tc_cpp3_09_public_runner", order: 1, visibility: "public", stdin: "runner\n", expectedStdout: "C++:runner\n" }, { id: "tc_cpp3_09_hidden_skill", order: 2, visibility: "hidden", stdin: "skill\n", expectedStdout: "C++:skill\n" }] }],
        }),
        cppLesson(chapterId, {
          id: "lesson_cpp3_10_functions",
          slug: "functions",
          title: "Lesson 10: 関数",
          objective: "関数を定義し、引数と戻り値を使って処理をまとめられる。",
          explanationMd: "関数は処理に名前を付けて再利用する仕組みです。returnで呼び出し元へ値を返せます。",
          taskMd: "整数を1つ受け取り、その2倍を返す関数 doubleNumber(number) を使って結果を出力してください。",
          starterCode: doubleStarter,
          sampleInput: "6\n",
          sampleOutput: "12\n",
          constraints: ["doubleNumber(int number) という関数を定義してください。", "doubleNumber()の中で number * 2 を返してください。", "入力値をdoubleNumber()へ渡してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 10,
          hints: ["戻り値のある関数は return を使います。", "2倍の値を返すには return number * 2; と書きます。", "std::cout << doubleNumber(value) << std::endl; と書くと戻り値を出力できます。"],
          exercises: [
            { id: "ex_cpp3_10_01", promptMd: "関数で2倍の計算をまとめ、入力値へ適用して出力します。", starterCode: doubleStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の2倍を出力する。", testCases: [{ id: "tc_cpp3_10_public_six", order: 1, visibility: "public", stdin: "6\n", expectedStdout: "12\n" }, { id: "tc_cpp3_10_hidden_eleven", order: 2, visibility: "hidden", stdin: "11\n", expectedStdout: "22\n" }] },
            { id: "ex_cpp3_10_02", promptMd: "関数で3倍の計算をまとめ、入力値へ適用して出力します。", starterCode: tripleStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の3倍を出力する。", testCases: [{ id: "tc_cpp3_10_ex2_public_four", order: 1, visibility: "public", stdin: "4\n", expectedStdout: "12\n" }, { id: "tc_cpp3_10_ex2_hidden_seven", order: 2, visibility: "hidden", stdin: "7\n", expectedStdout: "21\n" }] },
          ],
        }),
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
