import type { Course } from "../../../domain/curriculum";
import { javaLesson } from "../shared";

const courseId = "course_java_grade_3_foundation";
const chapterId = "chapter_java3_basic";

const printlnStarter = "public class Main {\n  public static void main(String[] args) {\n    System.out.println(\"Hello\");\n  }\n}\n";
const variableStarter = "public class Main {\n  public static void main(String[] args) {\n    String language = \"\";\n    System.out.println(language);\n  }\n}\n";
const inputStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    String name = scanner.nextLine();\n    System.out.println(\"Hello \" + name);\n  }\n}\n";
const operatorsStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int a = scanner.nextInt();\n    int b = scanner.nextInt();\n    System.out.println(a);\n    System.out.println(b);\n  }\n}\n";
const ifStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int score = scanner.nextInt();\n    if (score >= 60) {\n      System.out.println(\"OK\");\n    } else {\n      System.out.println(\"NG\");\n    }\n  }\n}\n";
const forStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int n = scanner.nextInt();\n    for (int i = 0; i < n; i++) {\n      System.out.println(i);\n    }\n  }\n}\n";
const whileStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int n = scanner.nextInt();\n    while (n > 0) {\n      System.out.println(n);\n    }\n  }\n}\n";
const arrayStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    String[] items = {scanner.nextLine(), scanner.nextLine(), scanner.nextLine()};\n    items[1] = \"?\";\n    System.out.println(items[0]);\n    System.out.println(items[1]);\n    System.out.println(items[2]);\n  }\n}\n";
const stringStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    String word = scanner.nextLine();\n    System.out.println(word);\n  }\n}\n";
const doubleStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static int doubleNumber(int number) {\n    return number;\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int value = scanner.nextInt();\n    System.out.println(doubleNumber(value));\n  }\n}\n";
const tripleStarter = "import java.util.Scanner;\n\npublic class Main {\n  public static int tripleNumber(int number) {\n    return number;\n  }\n\n  public static void main(String[] args) {\n    Scanner scanner = new Scanner(System.in);\n    int value = scanner.nextInt();\n    System.out.println(tripleNumber(value));\n  }\n}\n";

export const javaGrade3Course: Course = {
  id: courseId,
  languageId: "lang_java",
  levelId: "level_java_3",
  title: "Java 3級",
  description: "Javaの基礎をブラウザ上で実行・採点しながら学びます。",
  curriculumVersion: "java-grade-3-v0.1.0",
  validFrom: "2026-09-05",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "Java 3級 基礎",
      description: "出力、変数、入力、条件分岐、くり返し、配列、文字列、メソッドを練習します。",
      order: 1,
      lessons: [
        javaLesson(chapterId, {
          id: "lesson_java3_01_println",
          slug: "println",
          title: "Lesson 01: println / 出力",
          objective: "System.out.println()で指定された文字を標準出力へ表示できる。",
          explanationMd: "JavaではSystem.out.println()を使うと、かっこの中に書いた文字列や値を1行で出力できます。",
          taskMd: "System.out.println()を使って Hello, Programming Trainer! と1行で出力してください。",
          starterCode: printlnStarter,
          sampleInput: "",
          sampleOutput: "Hello, Programming Trainer!\n",
          constraints: ["class Main と main メソッドを残してください。", "出力は1行だけにしてください。", "大文字・小文字、記号、空白も一致させてください。"],
          difficulty: 1,
          estimatedMinutes: 10,
          order: 1,
          hints: ["文字列はダブルクォートで囲みます。", "System.out.println(\"Hello, Programming Trainer!\"); の形を思い出しましょう。"],
          exercises: [{ id: "ex_java3_01_01", promptMd: "指定された文字列を出力します。", starterCode: printlnStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で期待出力と一致する。", testCases: [{ id: "tc_java3_01_public", order: 1, visibility: "public", stdin: "", expectedStdout: "Hello, Programming Trainer!\n" }, { id: "tc_java3_01_hidden_exact", order: 2, visibility: "hidden", stdin: "", expectedStdout: "Hello, Programming Trainer!\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_02_variables",
          slug: "variables",
          title: "Lesson 02: 変数",
          objective: "String変数に値を入れ、その値を出力できる。",
          explanationMd: "変数は値に名前を付けて保存する仕組みです。String language = \"Java\"; のように書きます。",
          taskMd: "変数 language に Java を代入し、System.out.println(language) で出力してください。",
          starterCode: variableStarter,
          sampleInput: "",
          sampleOutput: "Java\n",
          constraints: ["変数名は language を使ってください。", "System.out.println()には変数 language を渡してください。"],
          difficulty: 1,
          estimatedMinutes: 12,
          order: 2,
          hints: ["String language = \"Java\"; と書きます。", "文字列を直接出すのではなく、変数を出力しましょう。"],
          exercises: [{ id: "ex_java3_02_01", promptMd: "変数に値を代入し、その変数を出力します。", starterCode: variableStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方に合格する。", testCases: [{ id: "tc_java3_02_public", order: 1, visibility: "public", stdin: "", expectedStdout: "Java\n" }, { id: "tc_java3_02_hidden_lines", order: 2, visibility: "hidden", stdin: "", expectedStdout: "Java\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_03_input",
          slug: "input",
          title: "Lesson 03: Scanner / 入力",
          objective: "Scannerで受け取った文字列を使って出力できる。",
          explanationMd: "Programming TrainerのJava実行環境では、ScannerのnextLine()やnextInt()で標準入力を受け取れます。",
          taskMd: "Scannerで名前を受け取り、Hello の後ろに名前を続けて出力してください。",
          starterCode: inputStarter,
          sampleInput: "Yosuke\n",
          sampleOutput: "Hello Yosuke\n",
          constraints: ["Scannerを使って入力を受け取ってください。", "Hello と入力値の間に空白を1つ入れてください。"],
          difficulty: 1,
          estimatedMinutes: 15,
          order: 3,
          hints: ["scanner.nextLine()の戻り値を name に代入します。", "\"Hello \" + name のように、文字列と変数を + でつなげます。"],
          exercises: [{ id: "ex_java3_03_01", promptMd: "標準入力から名前を受け取り、あいさつを出力します。", starterCode: inputStarter, completionCriteria: "複数の入力値で正しいあいさつを出力する。", testCases: [{ id: "tc_java3_03_public", order: 1, visibility: "public", stdin: "Yosuke\n", expectedStdout: "Hello Yosuke\n" }, { id: "tc_java3_03_hidden", order: 2, visibility: "hidden", stdin: "Mika\n", expectedStdout: "Hello Mika\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_04_types_operators",
          slug: "types-operators",
          title: "Lesson 04: 型と演算子",
          objective: "nextInt()で受け取った整数を使い、算術演算子で計算できる。",
          explanationMd: "intは整数を扱う型です。+ は足し算、* はかけ算に使います。",
          taskMd: "2行で整数を受け取り、1行目に合計、2行目に積を出力してください。",
          starterCode: operatorsStarter,
          sampleInput: "3\n4\n",
          sampleOutput: "7\n12\n",
          constraints: ["scanner.nextInt()を2回使ってください。", "合計、積の順に1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 4,
          hints: ["合計は a + b、積は a * b で求められます。", "System.out.println(a + b) と System.out.println(a * b) を別々の行に書きます。"],
          exercises: [{ id: "ex_java3_04_01", promptMd: "2つの整数を受け取り、合計と積を計算して出力します。", starterCode: operatorsStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、合計と積を正しい順序で出力する。", testCases: [{ id: "tc_java3_04_public", order: 1, visibility: "public", stdin: "3\n4\n", expectedStdout: "7\n12\n" }, { id: "tc_java3_04_hidden", order: 2, visibility: "hidden", stdin: "8\n5\n", expectedStdout: "13\n40\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_05_if",
          slug: "if",
          title: "Lesson 05: if",
          objective: "ifとelseを使い、条件に応じて違う処理を実行できる。",
          explanationMd: "ifは条件が成り立つときだけ波かっこの中の処理を実行します。",
          taskMd: "整数の点数を1つ受け取り、60以上なら pass、60未満なら retry と出力してください。",
          starterCode: ifStarter,
          sampleInput: "72\n",
          sampleOutput: "pass\n",
          constraints: ["scanner.nextInt()を1回使ってください。", "ifとelseを使って分岐してください。", "出力は pass または retry のどちらか1行にしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 5,
          hints: ["60以上かどうかは score >= 60 で判定できます。", "条件が成り立つ側で System.out.println(\"pass\") を実行します。", "else側にはretryの出力を書きます。"],
          exercises: [{ id: "ex_java3_05_01", promptMd: "点数を受け取り、合格か再挑戦かを条件分岐で出力します。", starterCode: ifStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、点数に応じた文字列を出力する。", testCases: [{ id: "tc_java3_05_public_pass", order: 1, visibility: "public", stdin: "72\n", expectedStdout: "pass\n" }, { id: "tc_java3_05_hidden_retry", order: 2, visibility: "hidden", stdin: "45\n", expectedStdout: "retry\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_06_for",
          slug: "for",
          title: "Lesson 06: for",
          objective: "forを使い、決まった回数だけ処理をくり返せる。",
          explanationMd: "forは同じ処理をくり返すときに使います。int i = 1で始め、i <= nの間くり返します。",
          taskMd: "整数 n を1つ受け取り、1から n までの整数を1行ずつ出力してください。",
          starterCode: forStarter,
          sampleInput: "3\n",
          sampleOutput: "1\n2\n3\n",
          constraints: ["scanner.nextInt()を1回使ってください。", "forを使ってくり返してください。", "1から入力値までを昇順で1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 6,
          hints: ["i = 0で始めると0から出力されます。", "1から始めたいときはint i = 1とします。", "for (int i = 1; i <= n; i++) の中で出力します。"],
          exercises: [{ id: "ex_java3_06_01", promptMd: "入力された数まで、forで数を順番に出力します。", starterCode: forStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、1から入力値までを正しく出力する。", testCases: [{ id: "tc_java3_06_public_three", order: 1, visibility: "public", stdin: "3\n", expectedStdout: "1\n2\n3\n" }, { id: "tc_java3_06_hidden_five", order: 2, visibility: "hidden", stdin: "5\n", expectedStdout: "1\n2\n3\n4\n5\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_07_while",
          slug: "while",
          title: "Lesson 07: while",
          objective: "whileを使い、条件が成り立つ間だけ処理をくり返せる。",
          explanationMd: "whileは条件がtrueの間、波かっこの中の処理をくり返します。",
          taskMd: "整数 n を1つ受け取り、n から1までの整数を1行ずつカウントダウンしてください。",
          starterCode: whileStarter,
          sampleInput: "3\n",
          sampleOutput: "3\n2\n1\n",
          constraints: ["scanner.nextInt()を1回使ってください。", "whileを使ってくり返してください。", "ループの中で n を1ずつ減らしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 7,
          hints: ["while (n > 0) と書くと、nが1以上の間くり返せます。", "出力のあとに n = n - 1; を書くと、次の回で値が小さくなります。", "nを減らし忘れるとループが終わらなくなります。"],
          exercises: [{ id: "ex_java3_07_01", promptMd: "whileで入力値から1までのカウントダウンを出力します。", starterCode: whileStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値から1までを正しく出力する。", testCases: [{ id: "tc_java3_07_public_three", order: 1, visibility: "public", stdin: "3\n", expectedStdout: "3\n2\n1\n" }, { id: "tc_java3_07_hidden_five", order: 2, visibility: "hidden", stdin: "5\n", expectedStdout: "5\n4\n3\n2\n1\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_08_array",
          slug: "array",
          title: "Lesson 08: array",
          objective: "配列を作り、インデックスで値を読み書きできる。",
          explanationMd: "配列は複数の値を順番にまとめる型です。items[0]は最初の値、items[1]は2番目の値を表します。",
          taskMd: "3行の文字列を受け取って配列に入れ、2番目の値を Java に変更してから、配列の3つの値を1行ずつ出力してください。",
          starterCode: arrayStarter,
          sampleInput: "red\nblue\ngreen\n",
          sampleOutput: "red\nJava\ngreen\n",
          constraints: ["scanner.nextLine()を3回使ってください。", "3つの値を配列に入れてください。", "2番目の要素は items[1] で更新してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 8,
          hints: ["String[] items = {...}; の形で配列を作れます。", "配列の2番目はitems[1]です。", "items[1] = \"Java\"; と書くと2番目の値を変更できます。"],
          exercises: [{ id: "ex_java3_08_01", promptMd: "配列の要素をインデックスで更新し、順番に出力します。", starterCode: arrayStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、2番目だけをJavaに変えた3行を出力する。", testCases: [{ id: "tc_java3_08_public_colors", order: 1, visibility: "public", stdin: "red\nblue\ngreen\n", expectedStdout: "red\nJava\ngreen\n" }, { id: "tc_java3_08_hidden_words", order: 2, visibility: "hidden", stdin: "cat\ndog\neel\n", expectedStdout: "cat\nJava\neel\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_09_string",
          slug: "string",
          title: "Lesson 09: String",
          objective: "Stringのメソッドを使って文字列を加工できる。",
          explanationMd: "Stringには文字列を加工するメソッドがあります。trim()は前後の空白を取り除き、toUpperCase()は大文字へ変換します。",
          taskMd: "1行の文字列を受け取り、前後の空白を除いて大文字にして出力してください。",
          starterCode: stringStarter,
          sampleInput: " java \n",
          sampleOutput: "JAVA\n",
          constraints: ["scanner.nextLine()を1回使ってください。", "trim()とtoUpperCase()を使ってください。", "出力は加工後の文字列1行にしてください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 9,
          hints: ["前後の空白は word.trim() で取り除けます。", "大文字にするには toUpperCase() を続けます。", "word.trim().toUpperCase() の形を試しましょう。"],
          exercises: [{ id: "ex_java3_09_01", promptMd: "文字列をtrim()とtoUpperCase()で整えて出力します。", starterCode: stringStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、加工後の文字列を出力する。", testCases: [{ id: "tc_java3_09_public_java", order: 1, visibility: "public", stdin: " java \n", expectedStdout: "JAVA\n" }, { id: "tc_java3_09_hidden_runner", order: 2, visibility: "hidden", stdin: " runner \n", expectedStdout: "RUNNER\n" }] }],
        }),
        javaLesson(chapterId, {
          id: "lesson_java3_10_methods",
          slug: "methods",
          title: "Lesson 10: メソッド",
          objective: "staticメソッドを定義し、引数と戻り値を使って処理をまとめられる。",
          explanationMd: "メソッドは処理に名前を付けて再利用する仕組みです。returnで呼び出し元へ値を返せます。",
          taskMd: "整数を1つ受け取り、その2倍を返すメソッド doubleNumber(number) を使って結果を出力してください。",
          starterCode: doubleStarter,
          sampleInput: "6\n",
          sampleOutput: "12\n",
          constraints: ["doubleNumber(int number) というstaticメソッドを定義してください。", "doubleNumber()の中で number * 2 を返してください。", "入力値をdoubleNumber()へ渡してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 10,
          hints: ["戻り値のあるメソッドは return を使います。", "2倍の値を返すには return number * 2; と書きます。", "System.out.println(doubleNumber(value)); と書くと戻り値を出力できます。"],
          exercises: [
            { id: "ex_java3_10_01", promptMd: "メソッドで2倍の計算をまとめ、入力値へ適用して出力します。", starterCode: doubleStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の2倍を出力する。", testCases: [{ id: "tc_java3_10_public_six", order: 1, visibility: "public", stdin: "6\n", expectedStdout: "12\n" }, { id: "tc_java3_10_hidden_eleven", order: 2, visibility: "hidden", stdin: "11\n", expectedStdout: "22\n" }] },
            { id: "ex_java3_10_02", promptMd: "メソッドで3倍の計算をまとめ、入力値へ適用して出力します。", starterCode: tripleStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の3倍を出力する。", testCases: [{ id: "tc_java3_10_ex2_public_four", order: 1, visibility: "public", stdin: "4\n", expectedStdout: "12\n" }, { id: "tc_java3_10_ex2_hidden_seven", order: 2, visibility: "hidden", stdin: "7\n", expectedStdout: "21\n" }] },
          ],
        }),
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
