import type { Lesson, Course } from "../../../domain/curriculum";

const courseId = "course_python_grade_3_foundation";
const chapterId = "chapter_py3_basic";

function publishedLesson(lesson: Lesson): Lesson {
  return lesson;
}

export const pythonGrade3Course: Course = {
  id: courseId,
  languageId: "lang_python",
  levelId: "level_python_3",
  title: "Python 3級",
  description: "Pythonの基礎をブラウザ上で実行・採点しながら学びます。",
  curriculumVersion: "python-grade-3-v0.9.0",
  validFrom: "2026-09-03",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "Python 3級 基礎",
      description: "Python 3級の基礎10Lessonを実装済みです。",
      order: 1,
      lessons: [
        publishedLesson({
          id: "lesson_py3_01_print",
          chapterId,
          slug: "print-output",
          title: "Lesson 01: print / 出力",
          objective: "print()を使って指定された文字を標準出力へ表示できる。",
          explanationMd: "Pythonではprint()を使うと、かっこの中に書いた文字列や値を画面へ出力できます。文字列は引用符で囲みます。",
          taskMd: "print()を使って Hello, Programming Trainer! と1行で出力してください。",
          starterCode: "print(\"Hello\")\n",
          sampleInput: "",
          sampleOutput: "Hello, Programming Trainer!\n",
          constraints: ["出力は1行だけにしてください。", "大文字・小文字、記号、空白も一致させてください。"],
          difficulty: 1,
          estimatedMinutes: 10,
          order: 1,
          status: "published",
          hints: ["文字列はダブルクォートまたはシングルクォートで囲みます。", "print(\"Hello, Programming Trainer!\") の形を思い出しましょう。"],
          exercises: [
            {
              id: "ex_py3_01_01",
              lessonId: "lesson_py3_01_print",
              type: "code",
              promptMd: "指定された文字列をprint()で出力します。",
              starterCode: "print(\"Hello\")\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "全ての必須TestCaseで期待出力と一致する。",
              testCases: [
                {
                  id: "tc_py3_01_public",
                  order: 1,
                  visibility: "public",
                  stdin: "",
                  expectedStdout: "Hello, Programming Trainer!\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_01_hidden_exact",
                  order: 2,
                  visibility: "hidden",
                  stdin: "",
                  expectedStdout: "Hello, Programming Trainer!\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_02_variables",
          chapterId,
          slug: "variables",
          title: "Lesson 02: 変数",
          objective: "変数に文字列を代入し、その値をprint()で出力できる。",
          explanationMd: "変数は値に名前を付けて保存する仕組みです。name = \"Python\" のように書くと、nameという変数へ文字列を代入できます。",
          taskMd: "変数 language に Python を代入し、print(language) で出力してください。",
          starterCode: "language = \"\"\nprint(language)\n",
          sampleInput: "",
          sampleOutput: "Python\n",
          constraints: ["変数名は language を使ってください。", "print()には変数 language を渡してください。"],
          difficulty: 1,
          estimatedMinutes: 12,
          order: 2,
          status: "published",
          hints: ["文字列 Python を変数へ入れるには language = \"Python\" と書きます。", "print(\"Python\") ではなく、変数を出力してみましょう。"],
          exercises: [
            {
              id: "ex_py3_02_01",
              lessonId: "lesson_py3_02_variables",
              type: "code",
              promptMd: "変数に値を代入し、その変数を出力します。",
              starterCode: "language = \"\"\nprint(language)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方に合格する。",
              testCases: [
                {
                  id: "tc_py3_02_public",
                  order: 1,
                  visibility: "public",
                  stdin: "",
                  expectedStdout: "Python\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_02_hidden_lines",
                  order: 2,
                  visibility: "hidden",
                  stdin: "",
                  expectedStdout: "Python\n",
                  comparator: "normalized_lines",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_03_input",
          chapterId,
          slug: "input",
          title: "Lesson 03: input / 入力",
          objective: "input()で受け取った文字列を使って出力できる。",
          explanationMd: "input()は標準入力から1行の文字列を受け取ります。受け取った値を変数に入れると、あとからprint()で使えます。",
          taskMd: "input()で名前を受け取り、Hello の後ろに名前を続けて出力してください。",
          starterCode: "name = input()\nprint(\"Hello\", name)\n",
          sampleInput: "Yosuke\n",
          sampleOutput: "Hello Yosuke\n",
          constraints: ["input()を1回使ってください。", "print(\"Hello\", name) のように、Hello と入力値の間に空白が入る形にしてください。"],
          difficulty: 1,
          estimatedMinutes: 15,
          order: 3,
          status: "published",
          hints: ["input()の戻り値を name に代入します。", "print()へ複数の値を渡すと、間に空白を入れて出力されます。"],
          exercises: [
            {
              id: "ex_py3_03_01",
              lessonId: "lesson_py3_03_input",
              type: "code",
              promptMd: "標準入力から名前を受け取り、あいさつを出力します。",
              starterCode: "name = input()\nprint(\"Hello\", name)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の入力値で正しいあいさつを出力する。",
              testCases: [
                {
                  id: "tc_py3_03_public",
                  order: 1,
                  visibility: "public",
                  stdin: "Yosuke\n",
                  expectedStdout: "Hello Yosuke\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_03_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "Python\n",
                  expectedStdout: "Hello Python\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_04_types_operators",
          chapterId,
          slug: "types-operators",
          title: "Lesson 04: 型と演算子",
          objective: "input()で受け取った文字列を数値へ変換し、算術演算子で計算できる。",
          explanationMd: "input()で受け取る値は文字列です。数値として計算したいときは int() で整数へ変換します。+ は足し算、* はかけ算に使います。",
          taskMd: "2行で整数を受け取り、1行目に合計、2行目に積を出力してください。",
          starterCode: "a = int(input())\nb = int(input())\nprint(a)\nprint(b)\n",
          sampleInput: "3\n4\n",
          sampleOutput: "7\n12\n",
          constraints: ["input()を2回使ってください。", "受け取った値は int() で整数に変換してください。", "合計、積の順に1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 4,
          status: "published",
          hints: [
            "input()の結果を int(input()) の形にすると、整数として扱えます。",
            "合計は a + b、積は a * b で求められます。",
            "print(a + b) と print(a * b) を別々の行に書くと、2行で出力できます。",
          ],
          exercises: [
            {
              id: "ex_py3_04_01",
              lessonId: "lesson_py3_04_types_operators",
              type: "code",
              promptMd: "2つの整数を受け取り、合計と積を計算して出力します。",
              starterCode: "a = int(input())\nb = int(input())\nprint(a)\nprint(b)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、合計と積を正しい順序で出力する。",
              testCases: [
                {
                  id: "tc_py3_04_public",
                  order: 1,
                  visibility: "public",
                  stdin: "3\n4\n",
                  expectedStdout: "7\n12\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_04_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "8\n5\n",
                  expectedStdout: "13\n40\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_05_if",
          chapterId,
          slug: "if",
          title: "Lesson 05: if",
          objective: "ifとelseを使い、条件に応じて違う処理を実行できる。",
          explanationMd: "ifは条件が成り立つときだけ、字下げされた処理を実行します。条件が成り立たないときの処理は else: の下に書きます。",
          taskMd: "整数の点数を1つ受け取り、60以上なら pass、60未満なら retry と出力してください。",
          starterCode: "score = int(input())\nif score >= 60:\n    print(\"OK\")\nelse:\n    print(\"NG\")\n",
          sampleInput: "72\n",
          sampleOutput: "pass\n",
          constraints: ["input()を1回使ってください。", "受け取った値は int() で整数に変換してください。", "ifとelseを使って分岐してください。", "出力は pass または retry のどちらか1行にしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 5,
          status: "published",
          hints: [
            "60以上かどうかは score >= 60 で判定できます。",
            "条件が成り立つ側の字下げブロックに print(\"pass\") を書きます。",
            "else: の下には、60未満のときの print(\"retry\") を書きます。",
          ],
          exercises: [
            {
              id: "ex_py3_05_01",
              lessonId: "lesson_py3_05_if",
              type: "code",
              promptMd: "点数を受け取り、合格か再挑戦かを条件分岐で出力します。",
              starterCode: "score = int(input())\nif score >= 60:\n    print(\"OK\")\nelse:\n    print(\"NG\")\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、点数に応じた文字列を出力する。",
              testCases: [
                {
                  id: "tc_py3_05_public_pass",
                  order: 1,
                  visibility: "public",
                  stdin: "72\n",
                  expectedStdout: "pass\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_05_hidden_retry",
                  order: 2,
                  visibility: "hidden",
                  stdin: "45\n",
                  expectedStdout: "retry\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_06_for",
          chapterId,
          slug: "for",
          title: "Lesson 06: for",
          objective: "forとrange()を使い、決まった回数だけ処理をくり返せる。",
          explanationMd: "forは同じ処理をくり返すときに使います。range(1, n + 1) は 1 から n までの整数を順番に作ります。",
          taskMd: "整数 n を1つ受け取り、1から n までの整数を1行ずつ出力してください。",
          starterCode: "n = int(input())\nfor i in range(n):\n    print(i)\n",
          sampleInput: "3\n",
          sampleOutput: "1\n2\n3\n",
          constraints: ["input()を1回使ってください。", "forを使ってくり返してください。", "1から入力値までを昇順で1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 6,
          status: "published",
          hints: [
            "range(n) は 0 から n - 1 までを作ります。",
            "1から始めたいときは range(1, n + 1) を使います。",
            "for i in range(1, n + 1): の下で print(i) を実行します。",
          ],
          exercises: [
            {
              id: "ex_py3_06_01",
              lessonId: "lesson_py3_06_for",
              type: "code",
              promptMd: "入力された数まで、forで数を順番に出力します。",
              starterCode: "n = int(input())\nfor i in range(n):\n    print(i)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、1から入力値までを正しく出力する。",
              testCases: [
                {
                  id: "tc_py3_06_public_three",
                  order: 1,
                  visibility: "public",
                  stdin: "3\n",
                  expectedStdout: "1\n2\n3\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_06_hidden_five",
                  order: 2,
                  visibility: "hidden",
                  stdin: "5\n",
                  expectedStdout: "1\n2\n3\n4\n5\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_07_while",
          chapterId,
          slug: "while",
          title: "Lesson 07: while",
          objective: "whileを使い、条件が成り立つ間だけ処理をくり返せる。",
          explanationMd: "whileは条件がTrueの間、字下げされた処理をくり返します。くり返しを終えるには、条件に使う値をループの中で変化させます。",
          taskMd: "整数 n を1つ受け取り、n から 1 までの整数を1行ずつカウントダウンしてください。",
          starterCode: "n = int(input())\nwhile n > 0:\n    print(n)\n",
          sampleInput: "3\n",
          sampleOutput: "3\n2\n1\n",
          constraints: ["input()を1回使ってください。", "whileを使ってくり返してください。", "ループの中で n を1ずつ減らしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 7,
          status: "published",
          hints: [
            "while n > 0: と書くと、n が1以上の間くり返せます。",
            "print(n) のあとに n = n - 1 を書くと、次の回で値が1つ小さくなります。",
            "n を減らし忘れると、ループが終わらなくなります。",
          ],
          exercises: [
            {
              id: "ex_py3_07_01",
              lessonId: "lesson_py3_07_while",
              type: "code",
              promptMd: "whileで入力値から1までのカウントダウンを出力します。",
              starterCode: "n = int(input())\nwhile n > 0:\n    print(n)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値から1までを正しく出力する。",
              testCases: [
                {
                  id: "tc_py3_07_public_three",
                  order: 1,
                  visibility: "public",
                  stdin: "3\n",
                  expectedStdout: "3\n2\n1\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_07_hidden_five",
                  order: 2,
                  visibility: "hidden",
                  stdin: "5\n",
                  expectedStdout: "5\n4\n3\n2\n1\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_08_list",
          chapterId,
          slug: "list",
          title: "Lesson 08: list",
          objective: "listを作り、インデックスで値を読み書きできる。",
          explanationMd: "listは複数の値を順番にまとめる型です。items[0] は最初の値、items[1] は2番目の値を表します。インデックスへ代入すると、その位置の値を更新できます。",
          taskMd: "3行の文字列を受け取ってリストに入れ、2番目の値を Python に変更してから、リストの3つの値を1行ずつ出力してください。",
          starterCode: "items = [input(), input(), input()]\nitems[1] = \"?\"\nprint(items[0])\nprint(items[1])\nprint(items[2])\n",
          sampleInput: "red\nblue\ngreen\n",
          sampleOutput: "red\nPython\ngreen\n",
          constraints: ["input()を3回使ってください。", "3つの値をlistに入れてください。", "2番目の要素は items[1] で更新してください。", "リストの値を順番に1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 8,
          status: "published",
          hints: [
            "3つの入力は [input(), input(), input()] の形でlistにできます。",
            "listの2番目は items[1] です。",
            "items[1] = \"Python\" と書くと、2番目の値を変更できます。",
          ],
          exercises: [
            {
              id: "ex_py3_08_01",
              lessonId: "lesson_py3_08_list",
              type: "code",
              promptMd: "listの要素をインデックスで更新し、順番に出力します。",
              starterCode: "items = [input(), input(), input()]\nitems[1] = \"?\"\nprint(items[0])\nprint(items[1])\nprint(items[2])\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、2番目だけをPythonに変えた3行を出力する。",
              testCases: [
                {
                  id: "tc_py3_08_public_colors",
                  order: 1,
                  visibility: "public",
                  stdin: "red\nblue\ngreen\n",
                  expectedStdout: "red\nPython\ngreen\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_08_hidden_words",
                  order: 2,
                  visibility: "hidden",
                  stdin: "cat\ndog\neel\n",
                  expectedStdout: "cat\nPython\neel\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_09_dict",
          chapterId,
          slug: "dict",
          title: "Lesson 09: dict",
          objective: "dictを使い、キーで値を読み書きできる。",
          explanationMd: "dictはキーと値を組み合わせて保存する型です。prices[\"apple\"] のようにキーを指定すると値を取り出せます。同じ形に代入すると値を更新できます。",
          taskMd: "商品名と新しい価格を1行ずつ受け取り、辞書 prices のその商品の価格を更新してから、更新後の価格を出力してください。",
          starterCode: "prices = {\"apple\": 100, \"banana\": 150}\nitem = input()\nnew_price = int(input())\nprices[item] = 0\nprint(prices[item])\n",
          sampleInput: "apple\n120\n",
          sampleOutput: "120\n",
          constraints: ["prices は dict として使ってください。", "商品名は input() で受け取ってください。", "新しい価格は int(input()) で整数に変換してください。", "prices[item] を更新してから出力してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 9,
          status: "published",
          hints: [
            "input()で受け取った商品名は item に入れます。",
            "新しい価格は int(input()) で整数に変換します。",
            "prices[item] = new_price と書くと、指定したキーの値を更新できます。",
          ],
          exercises: [
            {
              id: "ex_py3_09_01",
              lessonId: "lesson_py3_09_dict",
              type: "code",
              promptMd: "dictの値をキーで更新し、更新後の値を出力します。",
              starterCode: "prices = {\"apple\": 100, \"banana\": 150}\nitem = input()\nnew_price = int(input())\nprices[item] = 0\nprint(prices[item])\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、指定された商品の更新後価格を出力する。",
              testCases: [
                {
                  id: "tc_py3_09_public_apple",
                  order: 1,
                  visibility: "public",
                  stdin: "apple\n120\n",
                  expectedStdout: "120\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_09_hidden_banana",
                  order: 2,
                  visibility: "hidden",
                  stdin: "banana\n180\n",
                  expectedStdout: "180\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_10_functions",
          chapterId,
          slug: "functions",
          title: "Lesson 10: 関数",
          objective: "defで関数を定義し、引数と戻り値を使って処理をまとめられる。",
          explanationMd: "関数は処理に名前を付けて再利用する仕組みです。def double(number): の下に字下げして処理を書き、returnで呼び出し元へ値を返します。",
          taskMd: "整数を1つ受け取り、その2倍を返す関数 double(number) を使って結果を出力してください。",
          starterCode: "def double(number):\n    return number\n\nvalue = int(input())\nprint(double(value))\n",
          sampleInput: "6\n",
          sampleOutput: "12\n",
          constraints: ["double(number) という関数を定義してください。", "double() の中で number * 2 を返してください。", "input()で受け取った整数を double() に渡してください。"],
          difficulty: 2,
          estimatedMinutes: 18,
          order: 10,
          status: "published",
          hints: [
            "関数は def double(number): の形で定義します。",
            "2倍の値を返すには return number * 2 と書きます。",
            "print(double(value)) と書くと、関数の戻り値を出力できます。",
          ],
          exercises: [
            {
              id: "ex_py3_10_01",
              lessonId: "lesson_py3_10_functions",
              type: "code",
              promptMd: "関数で2倍の計算をまとめ、入力値へ適用して出力します。",
              starterCode: "def double(number):\n    return number\n\nvalue = int(input())\nprint(double(value))\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の2倍を出力する。",
              testCases: [
                {
                  id: "tc_py3_10_public_six",
                  order: 1,
                  visibility: "public",
                  stdin: "6\n",
                  expectedStdout: "12\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_10_hidden_eleven",
                  order: 2,
                  visibility: "hidden",
                  stdin: "11\n",
                  expectedStdout: "22\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
            {
              id: "ex_py3_10_02",
              lessonId: "lesson_py3_10_functions",
              type: "code",
              promptMd: "関数で3倍の計算をまとめ、入力値へ適用して出力します。",
              starterCode: "def triple(number):\n    return number\n\nvalue = int(input())\nprint(triple(value))\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の3倍を出力する。",
              testCases: [
                {
                  id: "tc_py3_10_ex2_public_four",
                  order: 1,
                  visibility: "public",
                  stdin: "4\n",
                  expectedStdout: "12\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_10_ex2_hidden_seven",
                  order: 2,
                  visibility: "hidden",
                  stdin: "7\n",
                  expectedStdout: "21\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
      ],
      challenges: [
        {
          id: "challenge_py3_basic_review",
          courseId,
          chapterId,
          kind: "chapter_challenge",
          slug: "basic-review",
          title: "Python 3級 章末課題: 基礎総復習",
          objective: "input、条件分岐、list、dict、関数を組み合わせて小さな集計処理を書ける。",
          descriptionMd: "Python 3級の10Lessonで扱った基礎文法をまとめて確認する章末課題です。",
          instructionsMd: "商品名と個数を受け取り、辞書から単価を取り出して合計金額を出力してください。個数が3以上なら最後に discount と出力します。",
          order: 1,
          status: "published",
          estimatedMinutes: 25,
          sourceLessonIds: [
            "lesson_py3_01_print",
            "lesson_py3_02_variables",
            "lesson_py3_03_input",
            "lesson_py3_04_types_operators",
            "lesson_py3_05_if",
            "lesson_py3_06_for",
            "lesson_py3_07_while",
            "lesson_py3_08_list",
            "lesson_py3_09_dict",
            "lesson_py3_10_functions",
          ],
          passingRequiredCount: 2,
          exercises: [
            {
              id: "ex_challenge_py3_basic_review_01",
              challengeId: "challenge_py3_basic_review",
              sourceLessonIds: [
                "lesson_py3_03_input",
                "lesson_py3_04_types_operators",
                "lesson_py3_05_if",
                "lesson_py3_09_dict",
                "lesson_py3_10_functions",
              ],
              type: "code",
              promptMd: "商品名と個数を受け取り、合計金額と割引対象かを出力します。",
              starterCode: "prices = {\"apple\": 120, \"banana\": 80}\n\n\ndef total_price(item, count):\n    return 0\n\nitem = input()\ncount = int(input())\nprint(total_price(item, count))\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、合計金額と必要な追加メッセージを正しく出力する。",
              testCases: [
                {
                  id: "tc_challenge_py3_basic_review_public",
                  order: 1,
                  visibility: "public",
                  stdin: "apple\n2\n",
                  expectedStdout: "240\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_challenge_py3_basic_review_hidden_discount",
                  order: 2,
                  visibility: "hidden",
                  stdin: "banana\n3\n",
                  expectedStdout: "240\ndiscount\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  mockExams: [
    {
      id: "mock_exam_py3_trial",
      courseId,
      slug: "trial",
      title: "Python 3級 模擬試験",
      descriptionMd: "Python 3級の基礎Lessonを横断して確認する模擬試験です。P3-03では開始、一時停止、問題移動、保存を確認します。",
      status: "published",
      timeLimitMinutes: 25,
      passingScorePercent: 100,
      problems: [
        {
          id: "problem_mock_py3_01_output",
          examId: "mock_exam_py3_trial",
          order: 1,
          sourceLessonIds: ["lesson_py3_01_print", "lesson_py3_02_variables"],
          type: "code",
          promptMd: "message 変数へ Python を入れて、その値を出力してください。",
          starterCode: "message = \"\"\nprint(message)\n",
          gradingMode: "stdout",
          timeoutMs: 3000,
          completionCriteria: "指定された文字列を1行で出力する。",
          testCases: [
            {
              id: "tc_mock_py3_01_public",
              order: 1,
              visibility: "public",
              stdin: "",
              expectedStdout: "Python\n",
              comparator: "trimmed_text",
              weight: 1,
              required: true,
            },
            {
              id: "tc_mock_py3_01_hidden",
              order: 2,
              visibility: "hidden",
              stdin: "",
              expectedStdout: "Python\n",
              comparator: "trimmed_text",
              weight: 1,
              required: true,
            },
          ],
        },
        {
          id: "problem_mock_py3_02_condition",
          examId: "mock_exam_py3_trial",
          order: 2,
          sourceLessonIds: ["lesson_py3_03_input", "lesson_py3_05_if"],
          type: "code",
          promptMd: "整数を1つ受け取り、偶数なら even、奇数なら odd と出力してください。",
          starterCode: "number = int(input())\nprint(number)\n",
          gradingMode: "stdout",
          timeoutMs: 3000,
          completionCriteria: "公開TestCaseで偶数の判定を正しく出力する。",
          testCases: [
            {
              id: "tc_mock_py3_02_public_even",
              order: 1,
              visibility: "public",
              stdin: "4\n",
              expectedStdout: "even\n",
              comparator: "trimmed_text",
              weight: 1,
              required: true,
            },
            {
              id: "tc_mock_py3_02_hidden_odd",
              order: 2,
              visibility: "hidden",
              stdin: "17\n",
              expectedStdout: "odd\n",
              comparator: "trimmed_text",
              weight: 1,
              required: true,
            },
          ],
        },
      ],
    },
  ],
};

