import type { Lesson, Course } from "../../../domain/curriculum";

const courseId = "course_python_grade_3_foundation";
const chapterId = "chapter_py3_basic";

function publishedLesson(lesson: Lesson): Lesson {
  return lesson;
}

function draftLesson(order: number, slug: string, title: string): Lesson {
  return {
    id: "lesson_py3_" + String(order).padStart(2, "0") + "_" + slug,
    chapterId,
    slug,
    title,
    objective: "今後のPhaseで実装します。",
    explanationMd: "このLessonはPhase 2以降で教材本文を追加します。",
    taskMd: "準備中です。",
    starterCode: "",
    sampleInput: "",
    sampleOutput: "",
    constraints: ["Phase 1では未実装です。"],
    difficulty: 1,
    estimatedMinutes: 10,
    order,
    status: "draft",
    hints: [],
    exercises: [],
  };
}

export const pythonGrade3Course: Course = {
  id: courseId,
  languageId: "lang_python",
  levelId: "level_python_3",
  title: "Python 3級",
  description: "Pythonの基礎をブラウザ上で実行・採点しながら学びます。",
  curriculumVersion: "python-grade-3-v0.5.0",
  validFrom: "2026-09-03",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "Python 3級 基礎",
      description: "出力、変数、入力、型と演算子、if、forの最初の6Lessonを実装済みです。",
      order: 1,
      lessons: [
        publishedLesson({
          id: "lesson_py3_01_print",
          chapterId,
          slug: "print-output",
          title: "Lesson 01: print / 出力",
          objective: "print()を使って指定された文字を標準出力へ表示できる。",
          explanationMd: "Pythonではprint()を使うと、かっこの中に書いた文字列や値を画面へ出力できます。文字列は引用符で囲みます。",
          taskMd: "print()を使って Hello, Programming Trainer! と1行で出力してください。",
          starterCode: "print(\"Hello\")\n",
          sampleInput: "",
          sampleOutput: "Hello, Programming Trainer!\n",
          constraints: ["出力は1行だけにしてください。", "大文字・小文字、記号、空白も一致させてください。"],
          difficulty: 1,
          estimatedMinutes: 10,
          order: 1,
          status: "published",
          hints: ["文字列はダブルクォートまたはシングルクォートで囲みます。", "print(\"Hello, Programming Trainer!\") の形を思い出しましょう。"],
          exercises: [
            {
              id: "ex_py3_01_01",
              lessonId: "lesson_py3_01_print",
              type: "code",
              promptMd: "指定された文字列をprint()で出力します。",
              starterCode: "print(\"Hello\")\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "全ての必須TestCaseで期待出力と一致する。",
              testCases: [
                {
                  id: "tc_py3_01_public",
                  order: 1,
                  visibility: "public",
                  stdin: "",
                  expectedStdout: "Hello, Programming Trainer!\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_01_hidden_exact",
                  order: 2,
                  visibility: "hidden",
                  stdin: "",
                  expectedStdout: "Hello, Programming Trainer!\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_02_variables",
          chapterId,
          slug: "variables",
          title: "Lesson 02: 変数",
          objective: "変数に文字列を代入し、その値をprint()で出力できる。",
          explanationMd: "変数は値に名前を付けて保存する仕組みです。name = \"Python\" のように書くと、nameという変数へ文字列を代入できます。",
          taskMd: "変数 language に Python を代入し、print(language) で出力してください。",
          starterCode: "language = \"\"\nprint(language)\n",
          sampleInput: "",
          sampleOutput: "Python\n",
          constraints: ["変数名は language を使ってください。", "print()には変数 language を渡してください。"],
          difficulty: 1,
          estimatedMinutes: 12,
          order: 2,
          status: "published",
          hints: ["文字列 Python を変数へ入れるには language = \"Python\" と書きます。", "print(\"Python\") ではなく、変数を出力してみましょう。"],
          exercises: [
            {
              id: "ex_py3_02_01",
              lessonId: "lesson_py3_02_variables",
              type: "code",
              promptMd: "変数に値を代入し、その変数を出力します。",
              starterCode: "language = \"\"\nprint(language)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方に合格する。",
              testCases: [
                {
                  id: "tc_py3_02_public",
                  order: 1,
                  visibility: "public",
                  stdin: "",
                  expectedStdout: "Python\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_02_hidden_lines",
                  order: 2,
                  visibility: "hidden",
                  stdin: "",
                  expectedStdout: "Python\n",
                  comparator: "normalized_lines",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_03_input",
          chapterId,
          slug: "input",
          title: "Lesson 03: input / 入力",
          objective: "input()で受け取った文字列を使って出力できる。",
          explanationMd: "input()は標準入力から1行の文字列を受け取ります。受け取った値を変数に入れると、あとからprint()で使えます。",
          taskMd: "input()で名前を受け取り、Hello の後ろに名前を続けて出力してください。",
          starterCode: "name = input()\nprint(\"Hello\", name)\n",
          sampleInput: "Yosuke\n",
          sampleOutput: "Hello Yosuke\n",
          constraints: ["input()を1回使ってください。", "print(\"Hello\", name) のように、Hello と入力値の間に空白が入る形にしてください。"],
          difficulty: 1,
          estimatedMinutes: 15,
          order: 3,
          status: "published",
          hints: ["input()の戻り値を name に代入します。", "print()へ複数の値を渡すと、間に空白を入れて出力されます。"],
          exercises: [
            {
              id: "ex_py3_03_01",
              lessonId: "lesson_py3_03_input",
              type: "code",
              promptMd: "標準入力から名前を受け取り、あいさつを出力します。",
              starterCode: "name = input()\nprint(\"Hello\", name)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "複数の入力値で正しいあいさつを出力する。",
              testCases: [
                {
                  id: "tc_py3_03_public",
                  order: 1,
                  visibility: "public",
                  stdin: "Yosuke\n",
                  expectedStdout: "Hello Yosuke\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_03_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "Python\n",
                  expectedStdout: "Hello Python\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_04_types_operators",
          chapterId,
          slug: "types-operators",
          title: "Lesson 04: 型と演算子",
          objective: "input()で受け取った文字列を数値へ変換し、算術演算子で計算できる。",
          explanationMd: "input()で受け取る値は文字列です。数値として計算したいときは int() で整数へ変換します。+ は足し算、* はかけ算に使います。",
          taskMd: "2行で整数を受け取り、1行目に合計、2行目に積を出力してください。",
          starterCode: "a = int(input())\nb = int(input())\nprint(a)\nprint(b)\n",
          sampleInput: "3\n4\n",
          sampleOutput: "7\n12\n",
          constraints: ["input()を2回使ってください。", "受け取った値は int() で整数に変換してください。", "合計、積の順に1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 4,
          status: "published",
          hints: [
            "input()の結果を int(input()) の形にすると、整数として扱えます。",
            "合計は a + b、積は a * b で求められます。",
            "print(a + b) と print(a * b) を別々の行に書くと、2行で出力できます。",
          ],
          exercises: [
            {
              id: "ex_py3_04_01",
              lessonId: "lesson_py3_04_types_operators",
              type: "code",
              promptMd: "2つの整数を受け取り、合計と積を計算して出力します。",
              starterCode: "a = int(input())\nb = int(input())\nprint(a)\nprint(b)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、合計と積を正しい順序で出力する。",
              testCases: [
                {
                  id: "tc_py3_04_public",
                  order: 1,
                  visibility: "public",
                  stdin: "3\n4\n",
                  expectedStdout: "7\n12\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_04_hidden",
                  order: 2,
                  visibility: "hidden",
                  stdin: "8\n5\n",
                  expectedStdout: "13\n40\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_05_if",
          chapterId,
          slug: "if",
          title: "Lesson 05: if",
          objective: "ifとelseを使い、条件に応じて違う処理を実行できる。",
          explanationMd: "ifは条件が成り立つときだけ、字下げされた処理を実行します。条件が成り立たないときの処理は else: の下に書きます。",
          taskMd: "整数の点数を1つ受け取り、60以上なら pass、60未満なら retry と出力してください。",
          starterCode: "score = int(input())\nif score >= 60:\n    print(\"OK\")\nelse:\n    print(\"NG\")\n",
          sampleInput: "72\n",
          sampleOutput: "pass\n",
          constraints: ["input()を1回使ってください。", "受け取った値は int() で整数に変換してください。", "ifとelseを使って分岐してください。", "出力は pass または retry のどちらか1行にしてください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 5,
          status: "published",
          hints: [
            "60以上かどうかは score >= 60 で判定できます。",
            "条件が成り立つ側の字下げブロックに print(\"pass\") を書きます。",
            "else: の下には、60未満のときの print(\"retry\") を書きます。",
          ],
          exercises: [
            {
              id: "ex_py3_05_01",
              lessonId: "lesson_py3_05_if",
              type: "code",
              promptMd: "点数を受け取り、合格か再挑戦かを条件分岐で出力します。",
              starterCode: "score = int(input())\nif score >= 60:\n    print(\"OK\")\nelse:\n    print(\"NG\")\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、点数に応じた文字列を出力する。",
              testCases: [
                {
                  id: "tc_py3_05_public_pass",
                  order: 1,
                  visibility: "public",
                  stdin: "72\n",
                  expectedStdout: "pass\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_05_hidden_retry",
                  order: 2,
                  visibility: "hidden",
                  stdin: "45\n",
                  expectedStdout: "retry\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        publishedLesson({
          id: "lesson_py3_06_for",
          chapterId,
          slug: "for",
          title: "Lesson 06: for",
          objective: "forとrange()を使い、決まった回数だけ処理をくり返せる。",
          explanationMd: "forは同じ処理をくり返すときに使います。range(1, n + 1) は 1 から n までの整数を順番に作ります。",
          taskMd: "整数 n を1つ受け取り、1から n までの整数を1行ずつ出力してください。",
          starterCode: "n = int(input())\nfor i in range(n):\n    print(i)\n",
          sampleInput: "3\n",
          sampleOutput: "1\n2\n3\n",
          constraints: ["input()を1回使ってください。", "forを使ってくり返してください。", "1から入力値までを昇順で1行ずつ出力してください。"],
          difficulty: 2,
          estimatedMinutes: 15,
          order: 6,
          status: "published",
          hints: [
            "range(n) は 0 から n - 1 までを作ります。",
            "1から始めたいときは range(1, n + 1) を使います。",
            "for i in range(1, n + 1): の下で print(i) を実行します。",
          ],
          exercises: [
            {
              id: "ex_py3_06_01",
              lessonId: "lesson_py3_06_for",
              type: "code",
              promptMd: "入力された数まで、forで数を順番に出力します。",
              starterCode: "n = int(input())\nfor i in range(n):\n    print(i)\n",
              gradingMode: "stdout",
              timeoutMs: 3000,
              completionCriteria: "公開TestCaseとhidden TestCaseの両方で、1から入力値までを正しく出力する。",
              testCases: [
                {
                  id: "tc_py3_06_public_three",
                  order: 1,
                  visibility: "public",
                  stdin: "3\n",
                  expectedStdout: "1\n2\n3\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
                {
                  id: "tc_py3_06_hidden_five",
                  order: 2,
                  visibility: "hidden",
                  stdin: "5\n",
                  expectedStdout: "1\n2\n3\n4\n5\n",
                  comparator: "trimmed_text",
                  weight: 1,
                  required: true,
                },
              ],
            },
          ],
        }),
        draftLesson(7, "while", "Lesson 07: while"),
        draftLesson(8, "list", "Lesson 08: list"),
        draftLesson(9, "dict", "Lesson 09: dict"),
        draftLesson(10, "functions", "Lesson 10: 関数"),
      ],
    },
  ],
};

