import type { Course } from "../../../domain/curriculum";
import { rubyLesson } from "../shared";

const courseId = "course_ruby_grade_3_foundation";
const chapterId = "chapter_ruby3_basic";

const putsStarter = 'puts "Hello"\n';
const variableStarter = 'language = ""\nputs language\n';
const inputStarter = 'name = gets.chomp\nputs "Hello #{name}"\n';
const operatorsStarter = 'a = gets.to_i\nb = gets.to_i\nputs a\nputs b\n';
const ifStarter = 'score = gets.to_i\nif score >= 60\n  puts "OK"\nelse\n  puts "NG"\nend\n';
const forStarter = 'n = gets.to_i\nfor i in 0..n\n  puts i\nend\n';
const whileStarter = 'n = gets.to_i\nwhile n > 0\n  puts n\nend\n';
const arrayStarter = 'first = gets.chomp\nsecond = gets.chomp\nthird = gets.chomp\nitems = [first, second, third]\nitems[1] = "?"\nputs items[0]\nputs items[1]\nputs items[2]\n';
const stringStarter = 'word = gets.chomp\nputs word\n';
const doubleStarter = 'def double_number(number)\n  return number\nend\n\nvalue = gets.to_i\nputs double_number(value)\n';
const tripleStarter = 'def triple_number(number)\n  return number\nend\n\nvalue = gets.to_i\nputs triple_number(value)\n';

export const rubyGrade3Course: Course = {
  id: courseId,
  languageId: "lang_ruby",
  levelId: "level_ruby_3",
  title: "Ruby 3級",
  description: "Rubyの基礎をブラウザ上で実行・採点しながら学びます。",
  curriculumVersion: "ruby-grade-3-v0.1.0",
  validFrom: "2026-09-05",
  chapters: [
    {
      id: chapterId,
      courseId,
      title: "Ruby 3級 基礎",
      description: "出力、変数、入力、条件分岐、くり返し、配列、文字列、メソッドを練習します。",
      order: 1,
      lessons: [
        rubyLesson(chapterId, { id: "lesson_ruby3_01_puts", slug: "puts", title: "Lesson 01: puts / 出力", objective: "putsで指定された文字を標準出力へ表示できる。", explanationMd: "Rubyではputsを使うと、値を1行で出力できます。", taskMd: "putsを使って Hello, Programming Trainer! と1行で出力してください。", starterCode: putsStarter, sampleInput: "", sampleOutput: "Hello, Programming Trainer!\n", constraints: ["出力は1行だけにしてください。", "大文字・小文字、記号、空白も一致させてください。"], difficulty: 1, estimatedMinutes: 10, order: 1, hints: ["文字列はダブルクォートで囲みます。", "puts \"Hello, Programming Trainer!\" の形を思い出しましょう。"], exercises: [{ id: "ex_ruby3_01_01", promptMd: "指定された文字列を出力します。", starterCode: putsStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で期待出力と一致する。", testCases: [{ id: "tc_ruby3_01_public", order: 1, visibility: "public", stdin: "", expectedStdout: "Hello, Programming Trainer!\n" }, { id: "tc_ruby3_01_hidden_exact", order: 2, visibility: "hidden", stdin: "", expectedStdout: "Hello, Programming Trainer!\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_02_variables", slug: "variables", title: "Lesson 02: 変数", objective: "変数に値を入れ、その値を出力できる。", explanationMd: "変数は値に名前を付けて保存する仕組みです。language = \"Ruby\" のように書きます。", taskMd: "変数 language に Ruby を代入し、putsで出力してください。", starterCode: variableStarter, sampleInput: "", sampleOutput: "Ruby\n", constraints: ["変数名は language を使ってください。", "putsには変数 language を渡してください。"], difficulty: 1, estimatedMinutes: 12, order: 2, hints: ["language = \"Ruby\" と書きます。", "文字列を直接出すのではなく、変数を出力しましょう。"], exercises: [{ id: "ex_ruby3_02_01", promptMd: "変数に値を代入し、その変数を出力します。", starterCode: variableStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方に合格する。", testCases: [{ id: "tc_ruby3_02_public", order: 1, visibility: "public", stdin: "", expectedStdout: "Ruby\n" }, { id: "tc_ruby3_02_hidden_lines", order: 2, visibility: "hidden", stdin: "", expectedStdout: "Ruby\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_03_input", slug: "input", title: "Lesson 03: gets / 入力", objective: "getsで受け取った文字列を使って出力できる。", explanationMd: "Programming TrainerのRuby実行環境では、getsで標準入力の1行を受け取れます。", taskMd: "getsで名前を受け取り、Hello の後ろに名前を続けて出力してください。", starterCode: inputStarter, sampleInput: "Yosuke\n", sampleOutput: "Hello Yosuke\n", constraints: ["gets.chompを使って入力を受け取ってください。", "Hello と入力値の間に空白を1つ入れてください。"], difficulty: 1, estimatedMinutes: 15, order: 3, hints: ["name = gets.chomp を用意します。", "\"Hello #{name}\" の形で文字列に変数を埋め込めます。"], exercises: [{ id: "ex_ruby3_03_01", promptMd: "標準入力から名前を受け取り、あいさつを出力します。", starterCode: inputStarter, completionCriteria: "複数の入力値で正しいあいさつを出力する。", testCases: [{ id: "tc_ruby3_03_public", order: 1, visibility: "public", stdin: "Yosuke\n", expectedStdout: "Hello Yosuke\n" }, { id: "tc_ruby3_03_hidden", order: 2, visibility: "hidden", stdin: "Mika\n", expectedStdout: "Hello Mika\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_04_types_operators", slug: "types-operators", title: "Lesson 04: 数値と演算子", objective: "gets.to_iで受け取った整数を使い、算術演算子で計算できる。", explanationMd: "gets.to_iは入力を整数として扱います。+ は足し算、* はかけ算に使います。", taskMd: "2つの整数を1行ずつ受け取り、1行目に合計、2行目に積を出力してください。", starterCode: operatorsStarter, sampleInput: "3\n4\n", sampleOutput: "7\n12\n", constraints: ["gets.to_iで整数を2つ受け取ってください。", "合計、積の順に1行ずつ出力してください。"], difficulty: 2, estimatedMinutes: 15, order: 4, hints: ["合計は a + b、積は a * b で求められます。", "putsを2回使って、別々の行に出力します。"], exercises: [{ id: "ex_ruby3_04_01", promptMd: "2つの整数を受け取り、合計と積を計算して出力します。", starterCode: operatorsStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、合計と積を正しい順序で出力する。", testCases: [{ id: "tc_ruby3_04_public", order: 1, visibility: "public", stdin: "3\n4\n", expectedStdout: "7\n12\n" }, { id: "tc_ruby3_04_hidden", order: 2, visibility: "hidden", stdin: "8\n5\n", expectedStdout: "13\n40\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_05_if", slug: "if", title: "Lesson 05: if", objective: "ifとelseを使い、条件に応じて違う処理を実行できる。", explanationMd: "ifは条件が成り立つときだけ、その中の処理を実行します。", taskMd: "整数の点数を1つ受け取り、60以上なら pass、60未満なら retry と出力してください。", starterCode: ifStarter, sampleInput: "72\n", sampleOutput: "pass\n", constraints: ["gets.to_iで整数を1つ受け取ってください。", "ifとelseを使って分岐してください。", "出力は pass または retry のどちらか1行にしてください。"], difficulty: 2, estimatedMinutes: 15, order: 5, hints: ["60以上かどうかは score >= 60 で判定できます。", "else側にはretryの出力を書きます。"], exercises: [{ id: "ex_ruby3_05_01", promptMd: "点数を受け取り、合格か再挑戦かを条件分岐で出力します。", starterCode: ifStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、点数に応じた文字列を出力する。", testCases: [{ id: "tc_ruby3_05_public_pass", order: 1, visibility: "public", stdin: "72\n", expectedStdout: "pass\n" }, { id: "tc_ruby3_05_hidden_retry", order: 2, visibility: "hidden", stdin: "45\n", expectedStdout: "retry\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_06_for", slug: "for", title: "Lesson 06: for", objective: "forを使い、決まった回数だけ処理をくり返せる。", explanationMd: "forは同じ処理をくり返すときに使います。1..n は1からnまでの範囲です。", taskMd: "整数 n を1つ受け取り、1から n までの整数を1行ずつ出力してください。", starterCode: forStarter, sampleInput: "3\n", sampleOutput: "1\n2\n3\n", constraints: ["gets.to_iで整数を1つ受け取ってください。", "forを使ってくり返してください。", "1から入力値までを昇順で1行ずつ出力してください。"], difficulty: 2, estimatedMinutes: 15, order: 6, hints: ["0から始めると0も出力されます。", "for i in 1..n の中で出力します。"], exercises: [{ id: "ex_ruby3_06_01", promptMd: "入力された数まで、forで数を順番に出力します。", starterCode: forStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、1から入力値までを正しく出力する。", testCases: [{ id: "tc_ruby3_06_public_three", order: 1, visibility: "public", stdin: "3\n", expectedStdout: "1\n2\n3\n" }, { id: "tc_ruby3_06_hidden_five", order: 2, visibility: "hidden", stdin: "5\n", expectedStdout: "1\n2\n3\n4\n5\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_07_while", slug: "while", title: "Lesson 07: while", objective: "whileを使い、条件が成り立つ間だけ処理をくり返せる。", explanationMd: "whileは条件がtrueの間、処理をくり返します。", taskMd: "整数 n を1つ受け取り、n から1までの整数を1行ずつカウントダウンしてください。", starterCode: whileStarter, sampleInput: "3\n", sampleOutput: "3\n2\n1\n", constraints: ["gets.to_iで整数を1つ受け取ってください。", "whileを使ってくり返してください。", "ループの中で n を1ずつ減らしてください。"], difficulty: 2, estimatedMinutes: 15, order: 7, hints: ["while n > 0 と書くと、nが1以上の間くり返せます。", "出力のあとに n = n - 1 を書くと、次の回で値が小さくなります。"], exercises: [{ id: "ex_ruby3_07_01", promptMd: "whileで入力値から1までのカウントダウンを出力します。", starterCode: whileStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値から1までを正しく出力する。", testCases: [{ id: "tc_ruby3_07_public_three", order: 1, visibility: "public", stdin: "3\n", expectedStdout: "3\n2\n1\n" }, { id: "tc_ruby3_07_hidden_five", order: 2, visibility: "hidden", stdin: "5\n", expectedStdout: "5\n4\n3\n2\n1\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_08_array", slug: "array", title: "Lesson 08: array", objective: "配列を作り、インデックスで値を読み書きできる。", explanationMd: "配列は複数の値を順番にまとめる仕組みです。items[0]は最初の値、items[1]は2番目の値を表します。", taskMd: "3つの文字列を1行ずつ受け取って配列に入れ、2番目の値を Ruby に変更してから、3つの値を1行ずつ出力してください。", starterCode: arrayStarter, sampleInput: "red\nblue\ngreen\n", sampleOutput: "red\nRuby\ngreen\n", constraints: ["gets.chompで3つの文字列を受け取ってください。", "3つの値を配列に入れてください。", "2番目の要素は items[1] で更新してください。"], difficulty: 2, estimatedMinutes: 18, order: 8, hints: ["items = [first, second, third] の形で配列を作れます。", "配列の2番目はitems[1]です。", "items[1] = \"Ruby\" と書くと2番目の値を変更できます。"], exercises: [{ id: "ex_ruby3_08_01", promptMd: "配列の要素をインデックスで更新し、順番に出力します。", starterCode: arrayStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、2番目だけをRubyに変えた3行を出力する。", testCases: [{ id: "tc_ruby3_08_public_colors", order: 1, visibility: "public", stdin: "red\nblue\ngreen\n", expectedStdout: "red\nRuby\ngreen\n" }, { id: "tc_ruby3_08_hidden_words", order: 2, visibility: "hidden", stdin: "cat\ndog\neel\n", expectedStdout: "cat\nRuby\neel\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_09_string", slug: "string", title: "Lesson 09: string", objective: "文字列を組み立てられる。", explanationMd: "Rubyでは #{} を使うと、文字列の中へ変数を埋め込めます。", taskMd: "1つの単語を受け取り、Ruby: の後ろにその単語を続けて出力してください。", starterCode: stringStarter, sampleInput: "runner\n", sampleOutput: "Ruby:runner\n", constraints: ["gets.chompで1つの単語を受け取ってください。", "Ruby: と入力値をつなげてください。"], difficulty: 2, estimatedMinutes: 18, order: 9, hints: ["word = gets.chomp を用意します。", "\"Ruby:#{word}\" と書くと文字列を組み立てられます。"], exercises: [{ id: "ex_ruby3_09_01", promptMd: "文字列を受け取り、接頭辞を付けて出力します。", starterCode: stringStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、加工後の文字列を出力する。", testCases: [{ id: "tc_ruby3_09_public_runner", order: 1, visibility: "public", stdin: "runner\n", expectedStdout: "Ruby:runner\n" }, { id: "tc_ruby3_09_hidden_skill", order: 2, visibility: "hidden", stdin: "skill\n", expectedStdout: "Ruby:skill\n" }] }]}),
        rubyLesson(chapterId, { id: "lesson_ruby3_10_methods", slug: "methods", title: "Lesson 10: メソッド", objective: "メソッドを定義し、引数と戻り値を使って処理をまとめられる。", explanationMd: "メソッドは処理に名前を付けて再利用する仕組みです。returnで呼び出し元へ値を返せます。", taskMd: "整数を1つ受け取り、その2倍を返すメソッド double_number(number) を使って結果を出力してください。", starterCode: doubleStarter, sampleInput: "6\n", sampleOutput: "12\n", constraints: ["double_number(number) というメソッドを定義してください。", "double_number()の中で number * 2 を返してください。", "入力値をdouble_number()へ渡してください。"], difficulty: 2, estimatedMinutes: 18, order: 10, hints: ["戻り値のあるメソッドは return を使います。", "2倍の値を返すには return number * 2 と書きます。", "puts double_number(value) と書くと戻り値を出力できます。"], exercises: [{ id: "ex_ruby3_10_01", promptMd: "メソッドで2倍の計算をまとめ、入力値へ適用して出力します。", starterCode: doubleStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の2倍を出力する。", testCases: [{ id: "tc_ruby3_10_public_six", order: 1, visibility: "public", stdin: "6\n", expectedStdout: "12\n" }, { id: "tc_ruby3_10_hidden_eleven", order: 2, visibility: "hidden", stdin: "11\n", expectedStdout: "22\n" }] }, { id: "ex_ruby3_10_02", promptMd: "メソッドで3倍の計算をまとめ、入力値へ適用して出力します。", starterCode: tripleStarter, completionCriteria: "公開TestCaseとhidden TestCaseの両方で、入力値の3倍を出力する。", testCases: [{ id: "tc_ruby3_10_ex2_public_four", order: 1, visibility: "public", stdin: "4\n", expectedStdout: "12\n" }, { id: "tc_ruby3_10_ex2_hidden_seven", order: 2, visibility: "hidden", stdin: "7\n", expectedStdout: "21\n" }] }]}),
      ],
      challenges: [],
    },
  ],
  mockExams: [],
};
